### ISSUE TITLE
Angular 10 - NativeScriptMaterialBottomSheetModule ModuleWithProviders without a generic

### ISSUE THREAD

**Issue by limux82** [nativescript-community/ui-material-components#169]
In Order to work with Angular 10 the module has to be migrated as indicated here https://angular.io/guide/migration-module-with-providers

**Error in compilation**
ERROR in node_modules/nativescript-material-bottomsheet/angular/bottomsheet.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (nativescript-material-bottomsheet/angular) which declares NativeScriptMaterialBottomSheetModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2 export declare class NativeScriptMaterialBottomSheetModule {

**Comment by farfromrefug** [comment]
What version are you using? Angular 10 comes with N 7.0 Which is a breaking change. You need to use the new plugins @nativescript-community/ui-material-...

**Comment by limux82** [comment]
Thanks I resolved installing the @nativescript-community/ui-material-
