### ISSUE TITLE
Open > close > re-open bottomsheet crashes iOS app

### ISSUE THREAD

**Issue by romandragan** [nativescript-community/ui-material-components#171]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS (all versions), both emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.7
- Cross-platform modules: 7.0.2
- iOS runtime: 7.0.0
- @nativescript-community/ui-material-bottomsheet: 4.0.10 

### Please, tell us how to recreate the issue in as much detail as possible. 
Open > close > re-open bottom sheet crashes the app with:

```
NativeScript encountered a fatal error: Uncaught Error: Attempted to assign to readonly property.
_showNativeBottomSheet(file: app/src/bottomsheet.ios.ts:379:9)
at showBottomSheet(file: app/src/bottomsheet-common.ts:133:17)
at Vue.$showBottomSheet(file: app/src/vue/index.ts:30:28)
```

Surrounding [this line](https://github.com/nativescript-community/ui-material-components/blob/master/src/bottomsheet/bottomsheet.ios.ts#L379) with `try-catch` solves the problem:

```
(controller as any).animated = true;
```

**Comment by farfromrefug** [comment]
@romandragan should be fixed in 4.0.11
