### ISSUE TITLE
Issue v 4.0.12 with Nativescript 7 Angular 10 - @nativescript-community/ui-material-bottomsheet

### ISSUE THREAD

**Issue by bellalMohamed** [nativescript-community/ui-material-components#177]
when using ```NativeScriptMaterialBottomSheetModule.forRoot()``` I get this error and

error NG1010: Value at position 5 in the NgModule.imports of AppModule is not a reference: [object Object]

```
 22     imports: [
                 ~
 23         NativeScriptModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 28         NativeScriptMaterialBottomSheetModule.forRoot()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 29     ],
    ~~~~~
```

PR, Attached

**Comment by rbudnar** [comment]
@bellalMohamed This might help get you going: https://github.com/nativescript-community/ui-material-components/issues/172#issuecomment-696101370

**Comment by bellalMohamed** [comment]
> @bellalMohamed This might help get you going: https://github.com/nativescript-community/ui-material-components/issues/172#issuecomment-696101370

I made a PR with the fix, not yet merged

#177
