### ISSUE TITLE
IOS app crashing on bottom sheet opening

### ISSUE THREAD

**Issue by rafalneves** [nativescript-community/ui-material-components#180]
I'm experiencing an issue that I'm unable to fix and already run out of ideas. When the bottom sheet opens, the app crashes due to "More than one layout child inside a ContentView":

![image](https://user-images.githubusercontent.com/4136503/93721732-d9b79580-fb89-11ea-81b2-2921662817dc.png)

This issue occurs only in IOS the same code works perfectly on Android.
And it occurs both in the emulator and in a physical device.

I'm calling it as follows:
```
  openFilters() {
    const options: BottomSheetOptions = {
      viewContainerRef: this.viewContainerRef,
      context: { products: this.products },
      dismissOnDraggingDownSheet: false
    };

    this.bottomSheet.show(FiltersModal, options).subscribe(result => {
      if (result) {
        ...
      }
    });
  }
```

Being that modal a simple component:
```
export class FiltersModal implements OnInit {
...
<Page class="filters-modal" [height]="tab === 'periodicity' ? 410 : 655">
  <StackLayout class="filters-container">
    <FlexboxLayout class="filters-header">
      <Label text="Filtros" class="filters-title"></Label>
    </FlexboxLayout>
    <FlexboxLayout orientation="horizontal" class="filter-tab-container">
```

Currently using 4.0.12 on NS 7.0.8 but the same happens with previous 4.x versions and on 3.x versions with NS 6.x I tried multiple ones.

This is called on a module that is lazy loaded - unsure if relevant, shouldn't be.
The component is inited on that module:
```
import { NativeScriptMaterialBottomSheetModule } from '@nativescript-community/ui-material-bottomsheet/angular';

@NgModule({
  imports: [
    NativeScriptCommonModule,
    StoreRoutingModule,
    NativeScriptUIListViewModule,
    NativeScriptMaterialBottomSheetModule.forRoot(),
    SharedModule,
  ],
```

**Comment by farfromrefug** [comment]
@rafalneves your error stack does not seem related to that comp. Can you share a repro sample? Cant do much without

**Comment by rafalneves** [comment]
@farfromrefug, here: https://bitbucket.org/rafalneves/bottomsheetsample

Btw, you will see a second issue related to angular 10 compatibilities.

**Comment by farfromrefug** [comment]
@rafalneves tested your app and it does not crash for me.

**Comment by rafalneves** [comment]
ah... hmm. How did you bypass the compiling issues related to angular 10 compatibilities?

**Comment by farfromrefug** [comment]
@rafalneves what error ? It ran that is sure as i have it running on my sim. And no crash there.
No for the angular issues i am sorry i cant really help, i know nothing about angular :D

**Comment by rafalneves** [comment]
The issue is solved in the latest version (5.x).
