### ISSUE TITLE
iOS app crashes with ripple plugin

### ISSUE THREAD

**Issue by romandragan** [nativescript-community/ui-material-components#183]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS
- iOS 14
- Emulator or device: both

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.9-rc1
- Cross-platform modules: 7.0.5
- Runtime(s): 7.0.0
- Plugin(s): 5.0.6

### Please, tell us how to recreate the issue in as much detail as possible. 
Open the app using ripple plugin on iOS, it will crash with `can't read colorWithAlphaComponent from null`. Seems like the issue is in this line: https://github.com/nativescript-community/ui-material-components/blob/master/src/ripple/ripple.ios.ts#L13, we need to check for `colorScheme.primaryColor` not to be null as well.

**Comment by farfromrefug** [comment]
@romandragan awesome man! will fix it right away

**Comment by farfromrefug** [comment]
@romandragan released. BTW i personally dont use Ripple anymore. Instead i use [mixins](https://github.com/nativescript-community/ui-material-components/blob/master/demo-vue/app/main.ts#L64). It brings `rippleColor` and `elevation` to all views.
This is important in the sense that it removes views in layout complexity
