### ISSUE TITLE
Can't change MDButton background color in dark mode on Android

### ISSUE THREAD

**Issue by butaminas** [nativescript-community/ui-material-components#192]
Which platform(s) does your issue occur on?

Android 10
Xiaomi Redmi Note 8

CLI: 7.0.8
Cross-platform modules: 7.0.3
Runtime(s): 7.0.0
Plugin(s):
  "dependencies": {
    "@mdi/font": "^5.6.55",
    "@nativescript-community/ui-material-activityindicator": "^5.0.6",
    "@nativescript-community/ui-material-bottomnavigationbar": "^5.0.6",
    "@nativescript-community/ui-material-bottomsheet": "^5.0.6",
    "@nativescript-community/ui-material-button": "^5.0.6",
    "@nativescript-community/ui-material-cardview": "^5.0.6",
    "@nativescript-community/ui-material-core": "^5.0.6",
    "@nativescript-community/ui-material-floatingactionbutton": "^5.0.6",
    "@nativescript-community/ui-material-progress": "^5.0.6",
    "@nativescript-community/ui-material-ripple": "^5.0.6",
    "@nativescript-community/ui-material-slider": "^5.0.6",
    "@nativescript-community/ui-material-tabs": "^5.0.6",
    "@nativescript-community/ui-material-textfield": "^5.0.6",
    "@nativescript-community/ui-material-textview": "^5.0.6",
    "@nativescript/firebase": "11.0.0",
    "@nativescript/core": "7.0.7",
    "@nativescript/theme": "3.0.0",
    "nativescript": "7.0.8",
    "nativescript-vue": "latest",
    "nativescript-vue-navigator": "^1.2.0",
    "vuex": "^3.5.1"
  },
  "devDependencies": {
    "@babel/core": "~7.11.6",
    "@babel/preset-env": "~7.11.5",
    "@nativescript/android": "7.0.0",
    "@nativescript/ios": "7.0.0",
    "@nativescript/webpack": "~3.0.5",
    "babel-loader": "~8.1.0",
    "nativescript-vue-template-compiler": "~2.8.1",
    "node-sass": "^4.7.1",
    "scss-symbols-parser": "^2.0.1",
    "string-replace-loader": "^2.3.0",
    "vue-loader": "~15.9.3",
    "vue-property-decorator": "^9.0.0"
  }

I'm trying to change the background color of a button via css like this:
 ```
 MDButton {
    &.-primary {
      color: #000;
      background-color: #fff;
      .ns-dark & {
        color: #fff;
        background-color: #000;
      }
    }
}
```

Unfortunately, the background color I get is some sort of dark gray.
It only occurs in dark mode and only on Android (testing on Xiaomi Redmi Note 8).

**Comment by farfromrefug** [comment]
@butaminas it works here. But i had to remove your `&.-primary`. What is that for?

**Comment by butaminas** [comment]
@farfromrefug the `-primary` class is my workaround for #188 problem right now.

After further investigation, I realized that this is not an issue with how the `MDButton` works but actually with how Android (or NativeScript on Android?) works. You can't have white (or close to white) backgrounds on dark mode in Android for some reason. That's why it was not working for me.  
After trying to change to a different color e.g. red or green - it started to work.

So in case you have any more info that you could share about this (or any workarounds) I would be happy to hear, otherwise, I will keep investigating to understand this better and there is no reason to keep this issue open as it is not an issue with the `MDButton` or `ui-material-components`.

**Comment by farfromrefug** [comment]
> You can't have white (or close to white) backgrounds on dark mode in Android for some reason. That's why it was not working for me.
Not sure what you mean but i have white background in dark mode. You can actually do whatever you want.
One thing though i dont use `@nativescript/theme` in css!!
![Screenshot_1601464713](https://user-images.githubusercontent.com/655344/94678867-79f68280-031f-11eb-8950-e3c5567553ce.png)
