### ISSUE TITLE
Bottomsheet: Android scroll behavior

### ISSUE THREAD

**Issue by cityinspain** [nativescript-community/ui-material-components#193]
### Which platform(s) does your issue occur on?
- Android
- Android version 10
- Emulator, Pixel 3

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.9-rc.2
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/@nativescript/core/package.json` file in your project)
- Runtime(s):     "@nativescript/android": "7.0.0",
- Plugin(s):  
 ```
"dependencies": {
    "@angular/animations": "~10.1.0",
    "@angular/common": "~10.1.0",
    "@angular/compiler": "~10.1.0",
    "@angular/core": "~10.1.0",
    "@angular/forms": "~10.1.0",
    "@angular/platform-browser": "~10.1.0",
    "@angular/platform-browser-dynamic": "~10.1.0",
    "@angular/router": "~10.1.0",
    "@nativescript-community/ui-material-bottomsheet": "^5.0.13",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~2.3.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~10.1.0",
    "@nativescript/android": "7.0.0",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "@ngtools/webpack": "~10.1.0",
    "@schematics/angular": "^10.1.4",
    "typescript": "~3.9.0"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 

The "swipe down to dismiss" behavior of the bottom sheet causes issues with scrolling content (in this case, a ListView). The user can scroll toward the bottom of the list, but scrolling up dismisses the bottom sheet. This can be avoided by scrolling down a small amount and then reversing direction without lifting your finger in a sort of "upside down check mark" motion.

### Is there any code involved? 

I've created an example repository to demonstrate this issue [here](https://github.com/cityinspain/mat-bottomsheet-scroll).

Is there maybe a way to disable the swipe to dismiss behavior?

**Comment by farfromrefug** [comment]
@cityinspain there are multiple wayd to handle that. See here https://github.com/nativescript-community/ui-material-components/blob/master/src/bottomsheet/bottomsheet-common.ts#L20.
I would use trackingScrollViee

**Comment by cityinspain** [comment]
That worked perfectly. Thanks so much for your help.

**Comment by ray007** [comment]
Can I get a hint how that solutions actually looks? Please?

**Comment by farfromrefug** [comment]
@ray007 i dont know what you want but using `trackingScrollView` is the solution to that issue

**Comment by ray007** [comment]
I have a bottomsheet with a listview inside. The listview can scroll the items.
I'm not sure to what I need set `trackingScrollView` so the event used for scrolling the listview are not used to drag the bottomsheet.
So far I haven't managed to track down either documentation or an example of using the property with nativescript.

**Comment by farfromrefug** [comment]
@ray007 please question should be on Slack. Github is to report bugs.
And the link in this issue was a link to the option where the comment is quite explicit: https://github.com/nativescript-community/ui-material-components/blob/f83947c1d647e924ad805e53c11677a0ea6b3303/src/bottomsheet/bottomsheet-common.ts#L27

**Comment by ray007** [comment]
I wouldn't call a short single line comment "explicit". So far my trial-and-error didn't produce anything working.
A small example would be really helpful here.

And I didn't know nativescript-community was on slack until now. Trying to join (after finding it with google search) I'm getting an error I need a `@telerik.com` email address for that.

I'm happy to take my questions to wherever is the right place to ask them 😃

**Comment by SidnevIgor** [comment]
@ray007 
If the question is still actual try to replace the listview or scrollview with a scrollview extension (https://github.com/ebarahona/nativescript-nested-scrollview). This did the trick for me
