### ISSUE TITLE
Bottomsheet content sliding to bottom when changed (Angular)

### ISSUE THREAD

**Issue by cityinspain** [nativescript-community/ui-material-components#199]
When updating content in a bottomsheet, padding at the top is introduced (when not specifying `ignoreTopSafeArea: false`).  

The padding that appears seems to be the same as the padding that is applied when ignoreTopSafeArea is set to false.

### Which platform(s) does your issue occur on?
Any iOS device with a "notch", running in an emulator.

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.10
- Cross-platform modules: 7.0.10
- Runtime(s): iOS 7.0.0
- Plugin(s): 
```javascript
    "dependencies": {
        "@angular/animations": "~10.1.3",
        "@angular/common": "~10.1.3",
        "@angular/compiler": "~10.1.3",
        "@angular/core": "~10.1.3",
        "@angular/forms": "~10.1.3",
        "@angular/platform-browser": "~10.1.3",
        "@angular/platform-browser-dynamic": "~10.1.3",
        "@angular/router": "~10.1.3",
        "@nativescript/core": "~7.0.7",
        "@nativescript/angular": "~10.1.5",
        "@nativescript-community/ui-material-activityindicator": "file:../packages/activityindicator",
        "@nativescript-community/ui-material-bottomsheet": "file:../packages/bottomsheet",
        "@nativescript-community/ui-material-bottomnavigationbar": "file:../packages/bottomnavigationbar",
        "@nativescript-community/ui-material-button": "file:../packages/button",
        "@nativescript-community/ui-material-cardview": "file:../packages/cardview",
        "@nativescript-community/ui-material-core": "file:../packages/core",
        "@nativescript-community/ui-material-dialogs": "file:../packages/dialogs",
        "@nativescript-community/ui-material-floatingactionbutton": "file:../packages/floatingactionbutton",
        "@nativescript-community/ui-material-progress": "file:../packages/progress",
        "@nativescript-community/ui-material-ripple": "file:../packages/ripple",
        "@nativescript-community/ui-material-slider": "file:../packages/slider",
        "@nativescript-community/ui-material-snackbar": "file:../packages/snackbar",
        "@nativescript-community/ui-material-textfield": "file:../packages/textfield",
        "@nativescript-community/ui-material-tabs": "file:../packages/tabs",
        "@nativescript/theme": "~3.0.0",
        "reflect-metadata": "~0.1.13",
        "rxjs": "~6.6.3",
        "zone.js": "~0.10.2"
    },
    "devDependencies": {
        "@angular/cli": "~10.1.3",
        "@angular/compiler-cli": "~10.1.3",
        "@nativescript/android": "7.0.0",
        "@nativescript/ios": "7.0.0",
        "@nativescript/types": "~7.0.4",
        "@nativescript/webpack": "~3.0.5",
        "@ngtools/webpack": "10.1.3"
    },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

Update the content shown in the bottomsheet's component in some way, such as toggling an *ngIf condition to show or hide something (such as a label), or adding an item to a listview.

### Is there any code involved? 

I've reproduced the issue in a [demo repo](https://github.com/cityinspain/ui-material-components/tree/demo-bottomsheet-sliding-issue/demo-ng) based on the Angular demo in this project, in the `demo-bottomsheet-sliding-issue` branch

**Comment by farfromrefug** [comment]
@cityinspain can you share a video? What if you use visibility instead of ngIf?

**Comment by cityinspain** [comment]
Yes, here's an GIF:

![bottomsheet-issue-demo](https://user-images.githubusercontent.com/21955158/96497863-4cfc0800-1219-11eb-9075-31291f60a751.gif)

The demo in the GIF is using visibility rather than *ngIf. The behavior is the same in both cases.

**Comment by farfromrefug** [comment]
@cityinspain fixed in latest version

**Comment by cityinspain** [comment]
Works great. Thanks so much!
