### ISSUE TITLE
Unable to dynamically add new TabContentItem to Tabs

### ISSUE THREAD

**Issue by romandragan** [nativescript-community/ui-material-components#200]
### Which platform(s) does your issue occur on?
- iOS/Android/**Both** 
- iOS 14 / Android 11
- emulator or device: both

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.9-rc.2
- Cross-platform modules: 7.0.11
- Runtime(s): iOS 7.0.3, Android 7.0.0
- Plugin(s): 5.0.23

### Please, tell us how to recreate the issue in as much detail as possible.
We're trying to generate tabs dynamically with:

```
<MDTabs
        ref="tabs"
        :selectedIndex="activeFeedIndex"
>
        <TabContentItem
          v-for="(item, $index) in items"
          :key="item.id"
        >
               <Label :text="item.name" />
       </TabContentItem>
</MDTabs>
```

Initial rendering woks fine. Removing an item from `items` works fine. Adding item to `items` array causes all tabs to be empty.

Is there any way to solve this?

**Comment by farfromrefug** [comment]
@romandragan i cant say this should be working. This components has been ported from N to here to keep "compatibility"
I do not really intent to maintain it  (and N team want to drop it too).
Maybe a PR :s Sorry....

**Comment by romandragan** [comment]
@farfromrefug, thanks... Do you know any other option to implement tabs with swipes in NS app?

**Comment by romandragan** [comment]
Nevermind, migrated to https://github.com/manijak/nativescript-carousel. Thanks anyway.
