### ISSUE TITLE
[BottomSheet] Right hand side of instanceof is not an object

### ISSUE THREAD

**Issue by nericode** [nativescript-community/ui-material-components#201]
### Make sure to check the existing issues in this repository 
-Yes
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS
- iOS 14.1
- emulator or device. What type of device? Emulator

### Please, provide the following version numbers that your issue occurs with:
```
{
  "nativescript": {
    "tns-ios": {
      "version": "6.5.3"
    },
    "tns-android": {
      "version": "6.5.3"
    }
  },
  "license": "",
  "repository": "",
  "scripts": {
    "lint": "tslint \"src/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "^3.0.0",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@nstudio/nativescript-loading-indicator": "^3.0.3",
    "nativescript-angular": "~8.20.3",
    "nativescript-camera": "^4.5.0",
    "nativescript-datetimepicker": "^1.2.2",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-image-cache-it": "^5.0.0-beta.6",
    "nativescript-image-zoom": "^3.0.3",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-material-bottomsheet": "^3.3.1",
    "nativescript-material-cardview": "^2.5.4",
    "nativescript-material-ripple": "^3.1.4",
    "nativescript-mercadopago-px": "^4.0.0",
    "nativescript-paypal-checkout": "^2.1.1",
    "nativescript-phone": "^1.4.1",
    "nativescript-secure-storage": "^2.6.0",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-tooltip-ns": "^1.0.3",
    "nativescript-ui-listview": "^8.0.1",
    "nativescript-ui-sidedrawer": "~8.0.0",
    "nativescript-version-number": "^1.1.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "^6.5.20",
    "validator": "^12.2.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "8.2.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-webpack": "^1.5.1",
    "node-sass": "^4.14.1",
    "tns-ios": "6.5.3",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  }
}
```

### Please, tell us how to recreate the issue in as much detail as possible. 
When I try open bottom sheet only show this message:
`
CONSOLE ERROR file: node_modules/@angular/core/fesm5/core.js:4002:0: ERROR TypeError: Right hand side of instanceof is not an object`

**Comment by farfromrefug** [comment]
@nericode I don't know much about angular. Plus it is 6.x branch so not my main focus. Also I would merge any PR on the 6.x branch

**Comment by wuilmerj24** [comment]
@nericode I have the same problem. Did you solve it?

**Comment by nericode** [comment]
@farfromrefug please check you new version, this` "nativescript-material-bottomsheet": "^3.2.8"` run fine!

@wuilmerj24 yes 👆

**Comment by farfromrefug** [comment]
@nericode don't understand what do you expect from me?

**Comment by sfrcnayds** [comment]
I have the same problem.

**Comment by EricBorland** [comment]
@sfrcnayds thanks for the fix! Anyone knows when would that be deployed into 3.3.2 or how can it be used right now? I'm stuck with this issue and the 3.3.1

**Comment by farfromrefug** [comment]
@EricBorland sorry will try and make a release today!

**Comment by sfrcnayds** [comment]
@farfromrefug Thank you
