### ISSUE TITLE
[Feature Request] Extended Floating Action Button

### ISSUE THREAD

**Issue by kryoware** [nativescript-community/ui-material-components#206]
Would it be possible to add this? Since this feature is cross-platform.

Sources:
[Android Implementation](https://material.io/develop/android/components/floating-action-button#extended-fabs)
[iOS Implementation](https://material.io/develop/ios/components/fabs#extended-fabs)

**Comment by farfromrefug** [comment]
Already there ;) did not have time to add the docs. Look at the button page in the vue demo app for an example

**Comment by kryoware** [comment]
@farfromrefug it doesn't seem to support this: [From Material Docs](https://kstatic.googleusercontent.com/files/b3bee069a3f5fda3ddcba1a613cb22d6302fe615e441d1de309f44734d01890e5e130fe9a172f6d07052adca0113468e5b1e839be075d1d8a66ee119ec3b6c37)

**Comment by farfromrefug** [comment]
@kryoware it does, simply add the logic in your app.
