### ISSUE TITLE
Error executing Static Binding Generator 

### ISSUE THREAD

**Issue by seankonig** [nativescript-community/ui-material-components#207]
Checked the examples

Could not find anything related

I can build to emulator just fine and that creates a debug apk which we can run on devices and all is good. If I try to build a release apk, I get the following error:

```
Error executing Static Binding Generator: Class not found com.google.android.material.bottomnavigation.BottomNavigationView.OnNavigationItemSelectedListener
Detailed log here: C:\projects\affsaf\ns360\platforms\android\build-tools\runSbg.log
```

The Log:

```
java.lang.RuntimeException: Class not found com.google.android.material.bottomnavigation.BottomNavigationView.OnNavigationItemSelectedListener
	at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:551)
	at org.nativescript.staticbindinggenerator.Generator.getInterfacesFromCache(Generator.java:534)
	at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:283)
	at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:171)
	at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:234)
	at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:121)
	at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:97)
	at org.nativescript.staticbindinggenerator.Main.main(Main.java:55)
```

### Which platform(s) does your issue occur on?
- Android 
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.8
- Cross-platform modules: 7.0.13
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): "dependencies": {
    "@angular/animations": "~10.1.3",
    "@angular/common": "~10.1.3",
    "@angular/compiler": "~10.1.3",
    "@angular/core": "~10.1.3",
    "@angular/forms": "~10.1.3",
    "@angular/platform-browser": "~10.1.3",
    "@angular/platform-browser-dynamic": "~10.1.3",
    "@angular/router": "~10.1.3",
    "@nativescript-community/ui-material-activityindicator": "^5.1.1",
    "@nativescript-community/ui-material-bottomnavigationbar": "^5.1.1",
    "@nativescript-community/ui-material-bottomsheet": "^5.1.1",
    "@nativescript-community/ui-material-button": "^5.1.1",
    "@nativescript-community/ui-material-cardview": "^5.1.1",
    "@nativescript-community/ui-material-dialogs": "^5.1.2",
    "@nativescript/angular": "~10.1.5",
    "@nativescript/core": "~7.0.7",
    "@nativescript/geolocation": "^7.0.0",
    "@nativescript/theme": "~3.0.0",
    "@nstudio/nativescript-mapbox": "^6.0.0-rc.0",
    "@nstudio/nativescript-snackbar": "^2.1.0",
    "moment": "^2.29.1",
    "nativescript-camera": "^4.5.0",
    "reflect-metadata": "~0.1.13",
    "rxjs": "^6.6.3",
    "tslint": "^6.1.3",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/cli": "^10.1.3",
    "@angular/compiler-cli": "~10.1.3",
    "@nativescript/android": "7.0.1",
    "@nativescript/ios": "7.0.0",
    "@nativescript/schematics": "^10.1.0",
    "@nativescript/types": "~7.0.4",
    "@nativescript/webpack": "~3.0.5",
    "@ngtools/webpack": "~10.1.3",
    "node-sass": "^4.14.1",
    "typescript": "~4.0.3"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
Create new project and add the @nativescript-community/ui-material-bottomnavigationbar plugin. I started with 5.0.? and updated it now to the latest, so the version is not an issue.

Try to create a release apk in Android Studio. Please let me know if you need more info. 

If this is an issue on my side, I would really appreciate it if someone could tell me where I am going wrong. Really new to all the Native Android stuff so this breaks my brain.

**Comment by farfromrefug** [comment]
Actually you package.json does not say what version you 
are using as you use ^.
It.might be a gradle version isssue. Need a reproducable repo

**Comment by seankonig** [comment]
Hey cool, I will try to install specific versions and see if I get the same error. I will try and do this tonight and give you feedback. Thanks for helping out

**Comment by seankonig** [comment]
Apologies for only getting back to you on this now. I traced the problem to the Android Gradle Plugin Version. The release APK does build out on 3.6.4. I update to 4.0.0 or higher it fails to build.
