### ISSUE TITLE
Bottom Navigation Bar - iOS v8 default selected tab

### ISSUE THREAD

**Issue by keerl** [nativescript-community/ui-material-components#208]
I'm having some issues with BottomNavigationBar when using v8 on iOS, it does not select a default tab and sometimes it actually crashes my app with a related error.

![Screen Shot 2020-11-10 at 6 21 28 AM](https://user-images.githubusercontent.com/24727492/98679978-01231700-231e-11eb-8c32-8c343372fad7.png)

![Screen Shot 2020-11-10 at 6 14 59 AM](https://user-images.githubusercontent.com/24727492/98679985-03857100-231e-11eb-9c77-8f1d1afbb282.png)

![Screen Shot 2020-11-10 at 6 19 58 AM](https://user-images.githubusercontent.com/24727492/98679835-d042e200-231d-11eb-97a7-f147e92aa140.png)

**Comment by farfromrefug** [comment]
Can you reproduce it with one of the demo apps?

**Comment by keerl** [comment]
Yeah, just run the vue demo. It uses `"tns-ios": "6.5.3"` by default so the problem doesn't exist. Switch to `"@nativescript/ios": "7.0.5"` and the problem will be there under the Bottom Navigation demo. It doesn't crash, but the problem is there (there is no default selected tab).

**Comment by butaminas** [comment]
I think this is related to https://github.com/nativescript-community/ui-material-components/issues/198
It doesn't work for me either on iOS (doesn't select first tab by default) and now I'm pretty sure it has to do something with `tns-ios 6.5.3`
