### ISSUE TITLE
Alerta view load component angular error

### ISSUE THREAD

**Issue by wuilmerj24** [nativescript-community/ui-material-components#210]
I am trying to use customview component but it generates error in angular Error: Failed to load component from module

Android device

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) 7.0.11 
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project): 
android:7.0.1

`alert({
      title:"",
      okButtonText:"",
      view: "../alerta-compare-clave/alerta-compare-clave.component",
    }).then(result => {
      alert(`closed  dialog with customview and result: ${result}`);
    });`

When trying to open the alert it generates the error Error: Failed to load component from module

**Comment by farfromrefug** [comment]
@wuilmerj24 seems like an angular issue. cant really help

**Comment by wuilmerj24** [comment]
thanks

**Comment by AgustinV08** [comment]
@wuilmerj24 how do you load the view in Angular?
