### ISSUE TITLE
BottomSheet: showingInBottomSheet and shownInBottomSheet events not called

### ISSUE THREAD

**Issue by felixkrautschuk** [nativescript-community/ui-material-components#212]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

I am trying to use your bottomsheet plugin for nativescript and I am able to show it, but its lifecycle events are not called both on Android and iOS.

This is what I am doing:

```
//main-page.ts
page.showBottomSheet({
        view: "bottomsheet-page",
        context: {
            foo: "bar"
        },
        closeCallback: (args) => {
            console.log(args);
        }
});
```

```
//bottomsheet-page.xml
<StackLayout showingInBottomSheet="onShowingInBottomSheet" shownInBottomSheet="onShownInBottomSheet">
    <Button text="close" tap="close"/>
</StackLayout>
```

```
//bottomsheet-page.ts
export function onShowingInBottomSheet() {
    console.log("onShowingInBottomSheet");
}

export function onShownInBottomSheet() {
    console.log("onShownInBottomSheet");
}

export function close() {
    console.log("close");
}
```

So I whould expect to see some console logs when the events are triggered but the code in the event handlers is not called. I only see the "close" message when I tap on the Button within the BottomSheet, but no other log.

I know that this issue is not new, due to https://github.com/nativescript-community/ui-material-components/issues/120 and https://github.com/nativescript-community/ui-material-components/issues/119 but as they were closed without any explanation.

I also tried to run your demo app, but I was not able to run it, so to waste not more time, I decided to create a fresh project and test it there... and I see the same behaviour as in my real app where I try to use the plugin.

### Which platform(s) does your issue occur on?
- Android & iOS
- tested on Android 7.1.1, Android 10, iOS 12.4 and iOS 13
- emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.13 (also tested 6.8.0)
- Cross-platform modules: 7.0.13 (also tested 6.5.20)
- Runtime(s): 7.0.0 (also tested 6.5.0)
- Plugin(s): @nativescript-community/ui-material-bottomsheet 5.1.8 (also tested nativescript-material-bottomsheet 3.3.1 with NS 6)

### Please, tell us how to recreate the issue in as much detail as possible. 
Run the demo apps provided below and open the bottom sheet by tapping the button, you should see two console logs but those will be missing.

### Is there any code involved? 
NS 6 with nativescript-material-bottomsheet 3.3.1:
[NSBottomSheetNS6.zip](https://github.com/nativescript-community/ui-material-components/files/5616206/NSBottomSheetNS6.zip)

NS 7 with @nativescript-community/ui-material-bottomsheet 5.1.8:
[NSBottomSheetNS7.zip](https://github.com/nativescript-community/ui-material-components/files/5616208/NSBottomSheetNS7.zip)

Would be nice if you could have a look and see what is going wrong.

**Comment by farfromrefug** [comment]
@felixkrautschuk found the source of the issue. Just figured out the Core XML builder will see your events only if the event name starts with `on...`. It works with Vue/Svelte/Angular but wont work with the core XML (which i dont use).
could the `loaded` event be enough for you right now?
I might look at this in the future but i dont want tot change the event names as it would be a breaking change

**Comment by felixkrautschuk** [comment]
@farfromrefug thanks for your investigations and your fast reply.

the `loaded` event would be a bit poor, there will be situtations for sure where we want to have separate events for "showing" and "shown". In addition, the loaded event does not give access to the context object in the event data.

So it seems to be pretty much without alternative to get those event handling working. :(

**Comment by farfromrefug** [comment]
@felixkrautschuk i disagree. There is no real difference with the loaded and my events. You can use loaded as layoutChange event. You will get the binding context of the object just like my events. Absolutely no difference there!
And you can register for the `shown` event from the `loaded` event. It is triggered after so it will work.

**Comment by felixkrautschuk** [comment]
@farfromrefug I tried to access `args.context` in the loaded event and it is undefined, like `args.object.navigationContext` is also undefined in the loaded event of a NativeScript Page as well (it is only available in navigatingTo and navigatedTo event, not the loaded event).

But you are right, I can register a handler for the `shownInBottomSheet` event from the loaded event of the sheet. It looks a bit weird, but it is working for now. Thanks for that hint.
