### ISSUE TITLE
TextField: build error on Android and iOS since plugin version 5.1.7 using NS 7

### ISSUE THREAD

**Issue by felixkrautschuk** [nativescript-community/ui-material-components#213]
### Make sure to check the demo app(s) for sample usage 
done

### Make sure to check the existing issues in this repository 
done

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

When creating a new project and adding the material textfield plugin via `tns plugin add @nativescript-community/ui-material-textfield`, the build fails during webpack with the following message:

> webpack is watching the files…
> ...
> ERROR in ../node_modules/@nativescript-community/ui-material-textfield/textfield.js
> Module not found: Error: Can't resolve '@nativescript-community/text' in '/Users/felixkrautschuk/PhpstormProjects/Testprojekte/nativescript-material-tf-ns7/node_modules/@nativescript-community/ui-material-textfield'
>  @ ../node_modules/@nativescript-community/ui-material-textfield/textfield.js 1:0-77 282:5-34
>  @ ./main-page.xml
>  @ . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$
>  @ ./app.ts

The last plugin version where I was able to build the app properly was **5.1.6**, the build fails for all the newer plugin versions including the latest plugin version 5.1.12.

### Which platform(s) does your issue occur on?
- Android and iOS
- no matter which os version
- emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.11
- Cross-platform modules: 7.0.13
- Runtime(s): tns/android 7.0.1, tns/ios 7.0.6
- Plugin(s): @nativescript-community/ui-material-textfield 5.1.7 to 5.1.12 (5.1.6 is latest working version)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

Create a new NS7 app and add the plugin > 5.1.6, or just take the provided sample app and try to run it (Android or iOS).

### Is there any code involved? 
[nativescript-material-tf-ns7.zip](https://github.com/nativescript-community/ui-material-components/files/5652139/nativescript-material-tf-ns7.zip)

**Comment by farfromrefug** [comment]
@felixkrautschuk sorry about this one ! I will release a fix

**Comment by farfromrefug** [comment]
@felixkrautschuk released a fix in 5.1.13

**Comment by felixkrautschuk** [comment]
@farfromrefug thanks for the fast reply and fix, it works now as expected.
