### ISSUE TITLE
How to use the showBadge method in Vue?

### ISSUE THREAD

**Issue by michaelsmedley** [nativescript-community/ui-material-components#214]
Hi

Really sorry, I don't have an issue as such, I'm more looking for advice really

I'm trying to display a notification badge within a nativescript-vue app and I'm really struggling to get it to work.

I have a menu all showing up functioning, I just want to add a badge to one of the tab items, but whatever I try I get an error similar to:

`this.$BottomNavigationBar.showBadge is not a function`

I tried doing this first within my main.js:

```
import BottomNavigationBar from 'nativescript-material-bottomnavigationbar/vue';
BottomNavigationBar.showBadge(0,20);
Vue.use(BottomNavigationBar);
```

which didn't work, so I tried binding it to my Vue instance (`Vue.prototype.$BottomNavigationBar = BottomNavigationBar`) so that I could try and run it within my component:

```
...
created () {
    this.$BottomNavigationBar.showBadge(0,20);
}
...
```

But again this through up the error mentioned above.

Feel like I am being really dumb here, but if anyone can help point me in the right direction I would be extremely grateful

Many thanks

**Comment by farfromrefug** [comment]
@michaelsmedley that is not how Vue or nativescript-vue works. You need to access the bottombar instance through `$refs` and then call the method on the `nativeView` instance. Please ask your questions first on Slack, you ll find much better support for that kind of questions.
We try to keep only real issues here. Thanks

**Comment by michaelsmedley** [comment]
@farfromrefug Thanks for getting back to me, and again apologies for not knowing what the correct protocol was for logging the query.

Is there a link to the slack you can share?  I tried going through the $refs approach you mentioned after I sent the message and was still getting a function not found error, so would be keen to follow this up

Thanks again

**Comment by michaelsmedley** [comment]
Ah geez it's all in the demo files isn't it - I really should have checked there first

Again, apologies for the waste of time - I do appreciate you pointing me in the right direction at least with your comment

**Comment by farfromrefug** [comment]
@michaelsmedley no problem, dont worry! here is the link to the slack https://nativescriptcommunity.slack.com/

**Comment by NavruzbekNoraliev** [comment]
> @michaelsmedley no problem, dont worry! here is the link to the slack https://nativescriptcommunity.slack.com/

how should we sign in there if we are not invited there ??

**Comment by farfromrefug** [comment]
@NavruzbekNoraliev https://join.slack.com/t/nativescriptcommunity/shared_invite/zt-kj28h204-6Y9uUTuNFxh_dKHNmlcwIg

**Comment by NavruzbekNoraliev** [comment]
> @NavruzbekNoraliev https://join.slack.com/t/nativescriptcommunity/shared_invite/zt-kj28h204-6Y9uUTuNFxh_dKHNmlcwIg

thanks for the invite, but this URL is sending me to sing in the page, and not allowing me in((

**Comment by farfromrefug** [comment]
@NavruzbekNoraliev maybe tried this one https://nativescriptcommunity.slack.com/join/shared_invite/zt-mglgp0ow-6a2eUgSd~DGHjD5o~hD~CA#/. It worked for me here

**Comment by NavruzbekNoraliev** [comment]
thanks it worked for me as well
