### ISSUE TITLE
[android] CSS/Classes no longer work on NS7.x

### ISSUE THREAD

**Issue by kryoware** [nativescript-community/ui-material-components#216]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Currently porting an existing NS6.x project to NS7.x but I notice the styles are no longer applied. (also when using `:class={ .. }`)

### Which platform(s) does your issue occur on?
- Android
- Tried on Android 9 & 11
- Device (Android 9) & Emulator (Android 11)

### Please, provide the following version numbers that your issue occurs with:

- CLI: `7.0.11`
- Cross-platform modules: `"@nativescript/core": "^7.0.3"`
- Runtime(s): `"@nativescript/android": "7.0.1"`
- Plugin(s): `"@nativescript-community/ui-material-textfield": "^5.1.12"` 

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
``` vue
<MDTextField
    ref="login_username"
    @focus="inputFocus"
    @blur="inputBlur"
    @textChange="onUsernameChange"

    hint="Email address or mobile no."
    returnKeyType="next"

    :text="user.email"

    :error="sampleError"
    errorEnabled="true"

    paddingLeft="0"
    paddingRight="0"

    background="white"
    placeholderColor="#808080"
    strokeColor="#004987"
    floatingColor="#004987"
    errorColor="#FF5460"
    class="__fs-16 __text-norm mb-2 px-0 mx-0"
/>
```
![Screenshot_20201211-130729_LI](https://user-images.githubusercontent.com/41801670/101867238-a4817900-3bb5-11eb-8779-77c195dcb4a3.jpg)

**Comment by farfromrefug** [comment]
@kryoware I can assure you that CSS classes still works. 
Your issue is somewhere else. If you want me to helpmyou need to narrow it down to speciifc props not applied and explain a bit more. Your screenshoot are good.but not self explanatory to someone out of your project.

**Comment by kryoware** [comment]
@farfromrefug I can reproduce it with a new NS7 project created using `tns create --vue` see: https://github.com/kryoware/md-demo/compare/start...end?diff=unified

And this is what it looks like, the style no longer gets applied to the text inside the field -- only the TextInputLayout gets styled.
![image](https://user-images.githubusercontent.com/41801670/101883954-f258aa00-3bd2-11eb-9c84-fa8c8bf31cad.png)

**Comment by farfromrefug** [comment]
@kryoware sorry but still not clear. Dont forget i dont know your code nor your app. What is not applied? Specify exactly what you pass, what is expected and what is seen.

**Comment by farfromrefug** [comment]
@kryoware your font issue should be fixed in latest version
