### ISSUE TITLE
Bottom Sheet: Sheet has extra padding top

### ISSUE THREAD

**Issue by AgustinV08** [nativescript-community/ui-material-components#222]
Updated Nativescript core to 7.1.0, webpack to 4.0 and ios platform to 7.1.0 versions. The sheet has an extra padding on top when showed on an ios device

This is my bottom sheet html 
<GridLayout class="sheet" ios:paddingBottom="30" rows="auto, 60, 60">

    <Label row="0" class="h2 margin bold" text="{{ 'sheets.camera-gallery.title' | L }}"></Label>

    <MDRipple row="1" class="ripple" (tap)="camera()" rippleColor="gray">

        <GridLayout columns="75 *">

            <Label col="0" class="fas margin icon" text="&#xf030;"></Label>
            <Label col="1" class="body regular" text="{{ 'sheets.camera-gallery.camera' | L }}"></Label>

        </GridLayout>

    </MDRipple>

    <MDRipple row="2" class="ripple" (tap)="gallery()" rippleColor="gray">

        <GridLayout columns="75, *">

            <Label col="0" class="fas margin icon" text="&#xf302;"></Label>
            <Label col="1" class="body regular" text="{{ 'sheets.camera-gallery.gallery' | L }}"></Label>

        </GridLayout>

    </MDRipple>

</GridLayout>

And my bottom sheet css 
```
.icon
{
    color: #6A6A6A;
    font-size: 20;
}

.margin
{
    margin-right: 15;
    margin-left: 15;
}

.ripple
{
    width: 100%;
    padding: 15, auto;
}

.sheet
{
    border-top-left-radius: 10;
    border-top-right-radius: 10;
}
```
This is how i show my bottom sheet 

```
        const options: BottomSheetOptions = {
            viewContainerRef: this.viewContainer,
            context: { },
            transparent: true,
            ignoreBottomSafeArea: true
        };

        this.bottomSheetService.show(CameraGallerySheetComponent, options).subscribe((result: string) =>
        {
            setTimeout(() =>
            {
                if (result)
                {
                    switch (result)
                    {
                        case "camera":
                            this.takePicture(document);
                            break;

                        case "gallery":
                            this.selectPicture(document);
                            break;
                    }
                }
            }, 500);
        });

```

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-01-05 at 16 52 21](https://user-images.githubusercontent.com/32682024/103709489-422f5480-4f78-11eb-8b04-5efa261c10f1.png)

Thanks in advance if someone has a solution for this, i have the 5.1.16 bottom sheet package

**Comment by farfromrefug** [comment]
@AgustinV08 you are facing this issue https://github.com/NativeScript/NativeScript/pull/9092.
You can fix it in the latest N versions 7.1 and using `iosIgnoreSafeArea` on the `GridLayout` (maybe others too dont remember).

**Comment by AgustinV08** [comment]
@farfromrefug using the iosIgnoreSafeArea property set to true gives the same result

```
<GridLayout rows="auto, 200, auto" iosIgnoreSafeArea="true">

    <Label row="0" class="fas margin text-left t-20" (tap)="closeModal()" text="&#xf00d;"></Label>

    <DrawingPad #signature row="1" class="signature margin" pendWidth="3" penColor="black"></DrawingPad>

    <GridLayout row="2" class="margin" columns="*, *">

        <Button col="0" class="button m-r-5 bold" (tap)="resetSignature()" text="{{ 'modals.contract.buttons.reset' | L }}"></Button>

        <Button col="1" class="button-success m-l-5 bold" (tap)="saveSignature()" text="{{ 'modals.contract.buttons.save' | L }}"></Button>

    </GridLayout>

</GridLayout>
```

**Comment by AgustinV08** [comment]
Sorry my bad, it indeed works, thank you @farfromrefug
