### ISSUE TITLE
Missing icons in bottom navigation bar

### ISSUE THREAD

**Issue by ray007** [nativescript-community/ui-material-components#225]
Usage for the bottom navigation bar says:

> Before start using the plugin you need to add the icons for Android & iOS in your `App_Resources`� directory.

Is there anywhere more specific documentation for that?

I tried to replicate the demo and I'm still missing the `ic_home` icon.

Or: is it possible to use icons from font-awesome or other icon fonts?

**Comment by farfromrefug** [comment]
@ray007 not sure without any code. Look at the vue demo (i am sure it works). If you have the demo running with icon then should have everything you need to set it up in your project

**Comment by ray007** [comment]
@farfromrefug thank you, I had hoped there would be an easier way to generate those stock-icons than track down a `png` and use some webservice.
I take it that's a no to support of icons from symbol fonts? Would also be nice for the floating action buttons.

**Comment by farfromrefug** [comment]
@ray007 it is ! look at N doc for using font icons.

**Comment by ray007** [comment]
@farfromrefug The only thing I found there is https://docs.nativescript.org/angular/ui/ng-components/icon-fonts, and that requires a `class` attribute to be set for the `Image` or `Label`.
Is there a way to set a `class` for the icon and use as `font://...`-resource in the navbar?
Or did I miss something else?

**Comment by farfromrefug** [comment]
@ray007 https://docs.nativescript.org/angular/ui/ng-components/icon-fonts

**Comment by ray007** [comment]
@farfromrefug thank you, but that's the same link I mentioned in my last comment.
And getting the icon depends on `class` to select the correct font.

So if there is an option to set `class` for the icon I have not yet found it.

**Comment by eikaramba** [comment]
i found a solution to use font icons! I'm using svelte, but the bindings are similar when using vue/angular/react etc.

`<bottomNavigationTab title="Profil" icon="{profilIcon}"  />`
```
let color = new Color(255, 255, 255, 255); //you can also use css to set text and icon color togehter. thus this gets ignored. In that case just provide null as color
let font = new Font("fa-solid-900", 18, "normal", "900");
let profilIcon = ImageSource.fromFontIconCodeSync("\uf007", font, color);
```

**Comment by ray007** [comment]
@eikaramba Thank you for reminding me, I did recently stumble over the documentation for `ImageSource.fromFontIconCodeSync` and thought to use it here when I found time...

**Comment by ZachPerkitny** [comment]
I feel like the API of `BottomNavigationBar` and `BottomNavigationTab` should be similar to the other `BottomNavigation` component and allow us to specify the contents. That would be ideal, the current API is very limited.

**Comment by farfromrefug** [comment]
@ZachPerkitny it is not that easy. It depends on what the native API let us do. You are welcome to have a go at it and create a PR

**Comment by ray007** [comment]
@farfromrefug adding a shortcut to get an icon from a font should be within what the API let's us do, no?

**Comment by farfromrefug** [comment]
@ray007 you mean using `fontIcon://&#xf1e0` for `icon` ? It is already working

**Comment by ray007** [comment]
@farfromrefug and which font will be used in your example?

**Comment by farfromrefug** [comment]
@ray007 i dont understand the question. you can use whatever font you want

**Comment by ZachPerkitny** [comment]
@farfromrefug Ahh ok, I'm not super familiar with the native API, did not know that was the limiting factor here.

And @ray007 is asking how do you specify the css class to use that defines a `font-family` property. Just defining `icon="font://&#xf1e0` does not work without it.

**Comment by farfromrefug** [comment]
@ray007 @ZachPerkitny i did not understand cause it was obvious to me as it works like any other component. simply apply a class to the component on which you use `icon="font://&#xf1e0"`

**Comment by ray007** [comment]
@farfromrefug I understand the theory, but the problem here is, a `<MDBottomNavigationTab>` has `title` and `icon` attributes, and `class` is not applied for the `icon`.
At least it wasn't last a tried, and if it was we'd probably have a problem with `title`.
Did I miss something?

**Comment by farfromrefug** [comment]
@ray007 it should be`iconClass` apparently (sorry i dont know all that code yet. It is a direct extract from the old N plugin).

**Comment by ray007** [comment]
@farfromrefug yes, that sounds like what I want.

But it does not seem to work. And looking through the code for `bottomnavigationbar` I can't find any mention of `iconClass`.

Searching through the repository I found `iconClass` in `src/core/tab-navigation-base/tab-strip-item/index.ts`, but that does not seem to be connected to the bottom navigationbar. And it does not seem to really be needed there...

**Comment by farfromrefug** [comment]
@ray007 i found the issue! will try to fix it and release

**Comment by bunower** [comment]
``> @ray007 i found the issue! will try to fix it and release
is this fixed?

`MDBottomNavigationBar
      activeColor="red"
      inactiveColor="yellow"
      backgroundColor="black"
      @tabSelected="onBottomNavigationTabSelected"
      row="1"
    >
      <MDBottomNavigationTab class="md" title="Second" icon="font://&#xe900;" />
      <MDBottomNavigationTab
        iconClass="md"
        class="md"
        title="Third"
        icon="String.fromCharCode(0xe900);"
      />
    `</MDBottomNavigationBar>`

for me nothing worked

**Comment by ray007** [comment]
No, at least it didn't when I tried a few days ago.

**Comment by farfromrefug** [comment]
@ray007 @bunower i checked here and it works fine. It is with material font right? Are you using `@mdi/font` ? Cause latest versions changed quite a bit (5.x).
The demo app correctly shows the icon https://github.com/nativescript-community/ui-material-components/blob/b6bd2ede114bd24f494f6d85d0627c7c6b35c825/demo-vue/app/examples/BottomNavigationBar.vue#L28 
But i use a webpack trick to replace the ligature texts

**Comment by ray007** [comment]
Hmm, I tried to show an icon from fontawesome:
``` html
<MDBottomNavigationTab title="Sensors" icon="font://&#xf294;" class="fab"/>
```
But that does not show the bluetooth-b it's supposed to show.

Further experimentation shows I apparently do not understand the decoding rules for the `font://` icon string.

Changing the tag to
``` html
<MDBottomNavigationTab title="Sensors" :icon="iconBt" class="fab"/>
```
and providing a property `iconBt` with `data()` as
``` javascript
iconBt: `font://${String.fromCodePoint(0xf294)}`
```
does work.

How does one translate this to a usable icon-string?
Or do I also need a webpack trick?

**Comment by ray007** [comment]
Update:
``` html
<MDBottomNavigationTab title="Sensors" icon.decode="font://&#xf294;" class="fab"/>
```
seems to do the trick. I am quite certain I did try that a while ago and it didn't work back then, but seems to work now.

**Comment by pradumnk-mahanta** [comment]
> Update:
> 
> ```
> <MDBottomNavigationTab title="Sensors" icon.decode="font://&#xf294;" class="fab"/>
> ```
> 
> seems to do the trick. I am quite certain I did try that a while ago and it didn't work back then, but seems to work now.

This does not work for me. 

I am implementing this on Angular Projects and tried everything, but could not get this to work directly.

```
<BottomNavigationTab title="Home" icon.decode="font://&#xf015;" class="fas"></BottomNavigationTab>
```

The only way it works is if I convert the font icon to ImageSource

```
<BottomNavigationTab title="Home" [icon]="homeIcon"></BottomNavigationTab>
```

and in TS,

```
let iconColor = new Color(255, 255, 255, 255);
let iconFont: Font;
if(isIOS)
    iconFont = new Font("Font Awesome 5 Free", 28, "normal", "900");
else
    iconFont = new Font("fa-solid-900", 28, "normal", "900");

this.homeIcon = ImageSource.fromFontIconCodeSync("\uf015", iconFont, iconColor);
```

**Comment by ray007** [comment]
I'm using Vue so I can't say much about angular. As I already wrote above, getting the actual character into the `font:` url also worked (with class attribute on tag). Try
``` typescript
this.homeIcon = "font://\uf015";
```

**Comment by ray007** [comment]
Note: unsurprisingly, this only works fine on android. On iOS, the icon sizes are very small...

**Comment by csimpi** [comment]
@farfromrefug This thread is full of misunderstandings, and still there isn't a clear way to handle this. Why is this closed? For me still doesn't work with Angular.

**Comment by farfromrefug** [comment]
@csimpi seems clear to me you should use something like `"font://\uf015"`. If it does not work with angular you are welcome to fix any angular related issue. Again i wont

**Comment by ray007** [comment]
An iOS icon size fix would still be nice...

**Comment by farfromrefug** [comment]
@ray007 we are talking `bottom-navigation` or `bottomnavigationbar` ?  if `bottom-navigation` i am seeing some `isIconSizeFixed` in the code (taken from the original N comp) which i dont know yet what it is doing. Could this is be it?

**Comment by ray007** [comment]
@farfromrefug I'm using `bottomnavigationbar`, so it's probably got nothing to do with `isIconSizeFixed`.

**Comment by csimpi** [comment]
He obviously doesn't want to understand the questions the people make here and throws the devs back to use old outdated versions... don't bother yourself too much with this repo, we'll need to work on our own solutions if we want to stick with NS. These community plugins are always frustrating to use for a long time. I have a lot of forked packages I maintain for myself... less frustrating that way, believe me. I'm going to start developing UI elements for myself from this point.

**Comment by farfromrefug** [comment]
@ray007 can you share a screenshot? This icon here https://github.com/nativescript-community/ui-material-components/blob/master/demo-vue/app/examples/BottomNavigationBar.vue#L28 looks good on iOS
<img width="261" alt="Screenshot 2021-08-16 at 16 42 02" src="https://user-images.githubusercontent.com/655344/129581958-f45d0ccc-1fcb-47b6-a7e7-671ade98fc88.png">
