### ISSUE TITLE
Bottom Navigation not persistent

### ISSUE THREAD

**Issue by HakobiDev** [nativescript-community/ui-material-components#231]
### Make sure to check the demo app(s) for sample usage 
Yes

### Make sure to check the existing issues in this repository 
Nothing exist

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- Android
-Android 10 & 9
- Pixel Devices, Xiaomi Devices

### Please, provide the following version numbers that your issue occurs with:
TNS Version : 7.1.2

```
   "@nativescript-community/ui-material-bottomnavigationbar": "^5.2.3",
   "@nativescript/android": "7.0.1",
   "@nativescript/core": "^7.1.4",
    "nativescript-vue": "^2.8.1",

  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/preset-env": "^7.11.5",
    "@nativescript/android": "7.0.1",
    "@nativescript/webpack": "^4.0.1",
    "babel-loader": "^8.1.0",
    "nativescript-vue-template-compiler": "^2.8.1",
    "nativescript-worker-loader": "~0.12.1",
    "sass": "^1.32.5",
    "vue-loader": "^15.9.3"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Obviously no need to provide reproduction playground.

In Vue

```
<Page>
 <GridLayout **v-if="currentTab === 0"**>
```
this will cause tearing all components and not persistent, In Bottom Navigation of Nativescript it retained the layout it will hidden from sight. In NC Material Bottom Navigation it will happened to rerender the whole layout as result we will got a GC hit/Performance Hit specially with lots of component in that particular tab.

Ex: Plugin UI_Pager

Nativescript Bottom Navigation Component:

1. if you navigate to index 3 of UI Pager
2. Go to Tab 3 of Bottom Navigation
3. Go Back to original tab with containing UI Pager
4. It will retained layout composition and position of index.

Nativescript Community Material Bottom Navigation Component

1. if you navigate to index 3 of UI Pager
2. Go to Tab 3 of Bottom Navigation
3. Go Back to original tab with containing UI Pager
4. It will start to reload and rendered whole layout and refetch items from any APIs although there is image caching but it will reparse the code that cause GC hit/Performance Hit.

In comparison: 
1. Same Loading time

NC Material Bottom Nav: 
Pros: 
Control over styling.
Cons: 
Always rerender the whole layout and force the component to reparse and load it

N Bottom Nav:
Pros: 
I described already above description
Cons:
Lack of events and out of the box styling method

Thanks.

**Comment by farfromrefug** [comment]
it is not an issue with this plugin. material bottom navigation bar only handles the bar itself.
what you are seeing comes from using vue v-if. you need to create a logic to achieve what you want

**Comment by HakobiDev** [comment]
Thank you for fast response, Sorry for miss conception of what the plugin does.

I resolved it from what you said that will need to create an own logic behind this plugin..

Ref for encounter with this instead using v-if or ng-switch

Vue:
```
:visibility="currentTab === 0 ? 'visible' : 'collapsed'"
``` 
Core
visibility="{{ currentTab === 0 ? 'visible' : 'collapsed' }}"

**Comment by farfromrefug** [comment]
@HakobiDev No worries. Also know that you can use `@nativescript-community/ui-material-bottomnavigationbar` with `BottomNavigation` (either from N or from `@nativescript-community/ui-material-bottom-navigation`, same extracted from N in the hope it gets removed from the core).
This is what i do on some project. The idea with using `BottomNavigation` is that tabs are only "loaded" on demand.
