### ISSUE TITLE
MDTextField: back button doesn't close the keyboard

### ISSUE THREAD

**Issue by yamuru** [nativescript-community/ui-material-components#232]
### Which platform(s) does your issue occur on?
- iOS/Android/Both = I am developing my app for Android.
- iOS/Android versions = All of my devices have different android versions.
- emulator or device. What type of device? = Real devices.

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) = 7.0.11
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/@nativescript/core/package.json` file in your project) = 7.0.13
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project) = This? "@nativescript/android": "7.0.1",
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here) = "dependencies": {
    "@nativescript-community/ui-material-activityindicator": "^5.1.12",
    "@nativescript-community/ui-material-bottomnavigationbar": "^5.1.12",
    "@nativescript-community/ui-material-bottomsheet": "^5.1.12",
    "@nativescript-community/ui-material-button": "^5.1.12",
    "@nativescript-community/ui-material-cardview": "^5.1.12",
    "@nativescript-community/ui-material-dialogs": "^5.2.3",
    "@nativescript-community/ui-material-floatingactionbutton": "^5.1.12",
    "@nativescript-community/ui-material-progress": "^5.1.12",
    "@nativescript-community/ui-material-ripple": "^5.1.12",
    "@nativescript-community/ui-material-slider": "^5.1.12",
    "@nativescript-community/ui-material-snackbar": "^5.1.12",
    "@nativescript-community/ui-material-textfield": "^5.1.12",
    "@nativescript-community/ui-material-textview": "^5.1.12",
    "@nativescript/core": "~7.0.0",
    "@vue/devtools": "^5.3.4",
    "nativescript-akylas-sqlite": "^3.0.5",
    "nativescript-fonticon": "^2.0.2",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-socketio": "^3.3.1",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-vue": "~2.8.0",
    "nativescript-vue-devtools": "^1.4.0",
    "vuex": "^3.6.0"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "^7.1.6",
    "@nativescript/android": "7.0.1",
    "@nativescript/webpack": "~3.0.0",
    "@vue/test-utils": "^1.1.2",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^26.6.3",
    "babel-loader": "~8.0.0",
    "jest": "^26.6.3",
    "nativescript-vue-template-compiler": "~2.8.0",
    "node-sass": "^4.7.1",
    "vue": "^2.6.12",
    "vue-jest": "^3.0.7",
    "vue-loader": "~15.9.3",
    "vue-template-compiler": "^2.6.12"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
I am kinda new to NativeScript and coding in general so maybe I am missing something.
I noticed that when I use dialog.prompt from this repository I can't press back button to close the keyboard after focusing on it.

Here is how I call it:
dialogs.prompt({
        title: null,
        textFieldProperties: {
          hint: 'Your weight',
        },
        okButtonText: 'Save',
        cancelButtonText: 'Cancel',
        autoFocus: true,
        inputType: dialogs.inputType.number,
        buttonTitleColor: new Color('#C77D6D'),
      }).then(...

I did a little "investigation" and learned that the dialog uses textfield from this repo.

So I placed MDTextField  on empty place in my app and yes - it doesn't close the keyboard on back button pressing too.

Simple TextField works good.

This is important because on my tablet the keyboard is above the save button.
It's ok I can close the keyboard by pressing checkmark button on my keyboard, but it's still an unexpected behaviour.

Have a good day, this repo is awesome :)

**Comment by farfromrefug** [comment]
@yamuru it works in the demo app of the project. NOt sure why it does not work on your device.  What are you running it on?

**Comment by yamuru** [comment]
@farfromrefug,
It doesn't work as expected on every device I checked on:
1. Samsung Galaxy J3 (Android: 5.1.1).
2. Lenovo TB-8703X (Tablet, Android 6.0.1).
3. Xiaomi Redmi 8 (Android 10).
4. XIaomi Redmi Note 4 (Android 7).

Today I tried to download the repo and launch the demo app to see if the problem is only inside of my project.
I did this:
npm i
npm run setup
npm run tsc-win (this is for windows, right?)

and faced this error:

> @nativescript-community/ui-material-core@5.2.3 tsc-win C:\Users\pc\Desktop\Coding\Projects\ui-material-components\packages\core
> ../../node_modules/.bin/cpy ..\..\src\core\core.d.ts .\ && ..\..\node_modules\.bin\tsc --skipLibCheck -d


lerna ERR! npm run tsc-win stderr:
".." �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nativescript-community/ui-material-core@5.2.3 tsc-win: `../../node_modules/.bin/cpy ..\..\src\core\core.d.ts .\ && ..\..\node_modules\.bin\tsc --skipLibCheck -d`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nativescript-community/ui-material-core@5.2.3 tsc-win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pc\AppData\Roaming\npm-cache\_logs\2021-02-04T12_54_10_936Z-debug.log

lerna ERR! npm run tsc-win exited 1 in '@nativescript-community/ui-material-core'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nativescript-community/ui-material-components@1.0.2 tsc-win: `lerna run tsc-win`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nativescript-community/ui-material-components@1.0.2 tsc-win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by farfromrefug** [comment]
@yamuru nice error :D damn windows...  I dont have windows around so cant really easily fix. Could you test on a linux system?

Now this is what happens on the demo app
https://user-images.githubusercontent.com/655344/106897703-96eafa00-66f3-11eb-85c9-187799ac6b1d.mp4

**Comment by yamuru** [comment]
@farfromrefug 

I tried a lot of things and it's still doesn't work:

- I kinda fixed `npm run tsc-win` and launched demo-vue - nope. So, we launched the same app and yours is ok and mine is not...
- ...and it can't be because of devices since things don't work on 4 different devices with different android versions. (not sure about this one)
- So I tried to reinstall my android sdk - nope. I started thinking maybe it's because of windows...
- ...and launched both demo-vue and my app on linux ubuntu 20.04 VM - nope.
- I opened `node_modules/@nativescript-community/ui-material-textfield/` and started putting `console.log`'s everywhere and found out that `clearFocus()` inside of `textfield.android.js` doesn't get called.
- Also on demo-vue app, when I do focus on textfield and press the back button, it logs that `blur` happened and then immediately logs `focus`

I am confused

**Comment by farfromrefug** [comment]
@yamuru mostly related to android native lib versions. The js part is not responsible for the back button. This is a full native behavior. You can play with versions like here:
https://github.com/nativescript-community/ui-material-components/blob/master/demo-vue/app/App_Resources/Android/before-plugins.gradle

**Comment by yamuru** [comment]
I DID IT YAAAY :D

The problem was here: `node_modules/@nativescript-community/ui-material-textfield/platforms/android/.../.../TextInputEditText.java`

```
...
...
    public boolean dispatchKeyEventPreIme(KeyEvent event) {
        if (imm != null && imm.isActive() && event.getAction() == android.view.KeyEvent.ACTION_UP
                && event.getKeyCode() == android.view.KeyEvent.KEYCODE_BACK) {
            // when hiding the keyboard with the back button also blur
            clearFocus(); // <--- no clearFocus here, there are view.clearFocus above, but this func doesn't have view parameter
            fullClearFocus(); // <--- this works
            return true;
        }
        return super.dispatchKeyEventPreIme(event);
    }

}
```

**Comment by farfromrefug** [comment]
@yamuru wow i am actually sorry :s really did not remember i implemented that!
Thank you so much for digging in and reporting the fix. 
Will release a fix
