### ISSUE TITLE
BottomSheet Android: dismissOnDraggingDownSheet prevents scrolling content

### ISSUE THREAD

**Issue by felixkrautschuk** [nativescript-community/ui-material-components#233]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

When setting `dismissOnDraggingDownSheet` to _true_, the user not able to scroll content within the BottomSheet anymore. The user can scroll down, but when trying to scroll up, it's just dragging down / closing the BottomSheet.
On iOS, everything works as expected.

![bottomsheet-drag-on-close](https://user-images.githubusercontent.com/6443021/106749788-46a66600-6627-11eb-8d3b-e9884bfd6ba3.gif)

The outer layout of the bottom sheet view looks like this:
```
<GridLayout rows="40,*">
    <ScrollView row="1">
        <StackLayout padding="10">
            <!-- ... -->
        </StackLayout>
    </ScrollView>
</GridLayout>
```

So with the first row using a fixed height, the user should be able to drag down / close the bottom sheet on iOS, but on Android this has no effect. It doe snot matter where the user starts the gesture, the bottom sheet is always getting closed.

@farfromrefug There is a similar problem with the RadSideDrawer on Android when it is getting opened from the top or the bottom. There you can call the native Method [setDrawerCloseThreshold](https://docs.telerik.com/devtools/android/androidcontrolsdoc/com/telerik/android/primitives/widget/sidedrawer/RadSideDrawer.html#setDrawerCloseThreshold-int-) to configure the height of the area, where the user can swipe down to close the drawer. Are you aware of something similar for the bottom sheet?

### Which platform(s) does your issue occur on?
- Android
- tested Android 6,9,10,11
- emulator andr device

### Please, provide the following version numbers that your issue occurs with:
- CLI: 7.1.2
- Cross-platform modules: @nativescript/core 7.1.4
- Runtime(s): @nativescript/android 7.0.1 and @nativescript/ios 7.1.1
- Plugin(s): @nativescript-community/ui-material-bottomsheet 5.2.3

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
Follow the steps shown in the GIF.

### Is there any code involved? 
[NSBottomSheetNS7.zip](https://github.com/nativescript-community/ui-material-components/files/5918587/NSBottomSheetNS7.zip)

**Comment by farfromrefug** [comment]
@felixkrautschuk did you try with `trackingScrollView` option ?  (id of the "scrollview")

**Comment by felixkrautschuk** [comment]
@farfromrefug yes I tried to set that, but it did not help.

**Comment by felixkrautschuk** [comment]
Btw, the `trackingScrollView` option is used only by iOS.

**Comment by farfromrefug** [comment]
@felixkrautschuk OK sorry misread. won't work with scrollview. you need to create a custom scrollview class which uses nestedscrollview native android class

**Comment by felixkrautschuk** [comment]
Ok, we will try that. Thanks for your fast feedback @farfromrefug

**Comment by farfromrefug** [comment]
@felixkrautschuk 
```
class NestedScrollView extends ScrollView {
    createNativeView() {
        if (global.isAndroid) {
            return new androidx.core.widget.NestedScrollView(this._context);
        }
        return super.createNativeView();
    }
}
```
that s enough!

**Comment by felixkrautschuk** [comment]
Nice, thank you @farfromrefug !
