### ISSUE TITLE
BottomSheet doesn't showed in device with Nativescript-Vue

### ISSUE THREAD

**Issue by ignacio68** [nativescript-community/ui-material-components#245]
### Make sure to check the demo app(s) for sample usage 

Not works

### Make sure to check the existing issues in this repository 

No issues

### If the demo apps cannot help and there is no issue for your problem, tell us about it

The child view is loaded but it isn't showed on the screen

### Which platform(s) does your issue occur on?

Platform: Android 8, 9

Device: Xiaomi Readmi Note 8T and many emulators.

### Please, provide the following version numbers that your issue occurs with:

![nativescript_info](https://user-images.githubusercontent.com/15833014/109155487-e3b07680-776f-11eb-920c-8b47c4e0bd02.JPG)
- Plugin(s): @nativescript-community/ui-material-bottomsheet: 5.2.8

### Please, tell us how to recreate the issue in as much detail as possible. 
When the button to load the bottom sheet is clicked,  the inner page is created and mounted but it's not showed on the device.

![BottomSheet](https://user-images.githubusercontent.com/15833014/109151200-28391380-776a-11eb-8abb-03ef97597a75.JPG)

### Is there any code involved? 
BottomSheet.vue

```
<template>
  <Page>
    <StackLayout height="100%">
     <MDButton text="Open Bottom Sheet" @tap="onTap" />
    </StackLayout>
  </Page>
</template>

<script lang="ts">
import Vue from 'nativescript-vue'
import { NativeScriptVue } from 'nativescript-vue'

import BottomSheetInner from './BottomSheetInner.vue'

export default Vue.extend({
  name: 'BottomSheet',

  methods: {
    onTap(args: EventData) {
       ;(this as NativeScriptVue).$showBottomSheet(BottomSheetInner,{})
    },
  },
})
</script>
```
BottomSheetInner.vue

```
<template>
  <StackLayout height="300" backgroundColor="yellow">
    <Label text="This is the Bottom Sheet Inner Page"></Label>
     <MDButton text="Close Bottom Sheet" @tap="onTap" />
    </StackLayout>
</template>

<script lang="ts">
  import Vue from 'nativescript-vue'
  import { NativeScriptVue } from 'nativescript-vue'

  export default Vue.extend({
    name: 'BottomSheetInner',

    created() {
      console.log('BottomSheetInner::created()')
    },

    mounted() {
      console.log('BottomSheetInner::mounted()')
    },

    methods: {
      onTap() {
        ;(this as NativeScriptVue).$closeBottomSheet()
      },
    },
  })
</script>
```

**Comment by farfromrefug** [comment]
I don't see anything wrong with your code. it should work. could you try the demo app from this repo ?( vue one)
run `npm run build` at root. then go.into demo-vue and run it. 
let me know if it still does not work .

**Comment by ignacio68** [comment]
I can't build the the project when I run `npm run build`. I receive a Lerna error message:

```
lerna notice cli v4.0.0
lerna info Executing command in 17 packages: "npm run tsc"
lerna ERR! npm run tsc exited 1 in '@nativescript-community/ui-material-core'
lerna ERR! npm run tsc stdout:

> @nativescript-community/ui-material-core@5.2.8 tsc
> ../../node_modules/.bin/cpy '**/*.d.ts' '../../packages/core' --cwd=../../src/core --parents && ../../node_modules/.bin/tsc --skipLibCheck -d

lerna ERR! npm run tsc stderr:
".." No such file or directory
lerna ERR! npm run tsc exited 1 in '@nativescript-community/ui-material-core'
```
I don't know anything about Lerna but I think that it's an error with `tsc` command.

**Comment by Fabiyo-90** [comment]
I have the same problem, this plugin it is not working.
I am on nativescript@7.0 with nativescript-vue.

**Comment by farfromrefug** [comment]
@ignacio68 @Fabiyo-90 did you set a height to the bottom sheet content ?

**Comment by ignacio68** [comment]
> @ignacio68 @Fabiyo-90 did you set a height to the bottom sheet content ?

@farfromrefug, yes the content page has height. 

```
<template>
  <StackLayout height="600" backgroundColor="yellow">
    <Label text="This is the Bottom Sheet Inner Page"></Label>
     <MDButton text="Close Bottom Sheet" @tap="onTap" />
    </StackLayout>
</template>
```

**Comment by ignacio68** [comment]
I use nativescript@7.x and nativescript-vue too.

**Comment by farfromrefug** [comment]
@Fabiyo-90 thank you !!!

**Comment by ignacio68** [comment]
Thanks @Fabiyo-90 , it works fine.
