### ISSUE TITLE
Ripple prevents ListView item tap event

### ISSUE THREAD

**Issue by PackagedCat** [nativescript-community/ui-material-components#247]
Sorry for may bad english.

Long time ago after updating Ripple plugin it began prevent ListView item tap event event without its own handler. Now I started to study the reason for this and after viewing the history of changes, I noticed to you remove (commended) `this.nativeView.setClickable(false);` in `initNativeView` method [fc48915](https://github.com/nativescript-community/ui-material-components/commit/2840b4d2ccda6f392ec5185d2974fbd5831cd127#diff-466809f92f1a1a8c2b39531d26e1bf53bfac84ea854bded175d93d8704454ade). After it was restored the itemTap event in ListView has started work.

I tried to figure out what is going on in next section, but I didn't succeed:
https://github.com/nativescript-community/ui-material-components/blob/372b3b58a8f249f023d0b677f9d41e480a0b9af9/src/ripple/ripple.android.ts#L209-L223

Can you explain why you forcing `setOnTouchListener ` in `initNativeView` and trying prevent call `hasGestureObservers` method in such a short period of time?
After remove all of this code, Ripple still works well (tap on Ripple and itemTap in ListView works too).

**Comment by farfromrefug** [comment]
@PackagedCat if i remember correctly without it the ripple does not work.

**Comment by PackagedCat** [comment]
@farfromrefug I tested on real device with Android 10 without that code block and Ripple works great. Maybe you remember in which cases may cause problems?

**Comment by farfromrefug** [comment]
@PackagedCat not really and I don't use MDRipple to create ripple effects ;) 
I use the mixin to get rippleColor.on any view.
can you create a PR?

**Comment by PackagedCat** [comment]
@farfromrefug Yes, that why I created this issue. I just I'm afraid to break something.

> I use the mixin to get rippleColor.on any view.

How? :)

**Comment by farfromrefug** [comment]
@PackagedCat https://github.com/nativescript-community/ui-material-components/blob/master/src/core/index.d.ts#L57

**Comment by wuilmerj24** [comment]
Same problem

**Comment by PackagedCat** [comment]
@wuilmerj24 Fixed in 5.2.10

**Comment by wuilmerj24** [comment]
@PackagedCat  Thns bro.
