### ISSUE TITLE
[BottomSheet] closeCallback does nothing when called after a second modal was shown

### ISSUE THREAD

**Issue by toverux** [nativescript-community/ui-material-components#250]
Hi,

When I'm opening a bottom sheet on top of another bottom sheet, the `closeCallback` from the first bottom sheet does nothing when called.

I am able to show multiple modals at the same time, but I'm only able to close the latest one that was opened.

The system back button works, however, I'm able to close the first modal with it.

Actually, I did some more tests and calling the close callback from the first sheet while the second sheet is still opened, closes the second sheet instead of the first one. I guess they share an underlying controller instance. I hope this could be easily improved so a modal always a close callback that's specific to it.

### Which platform(s) does your issue occur on?
- iOS
- Android

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.2.0
- Cross-platform modules: 7.2.1
- Runtime(s): Android 7.0.1, iOS 7.2.0

### Please, tell us how to recreate the issue in as much detail as possible. 

 - Open modal A **[OK]**
 - Open modal B from inside A, without closing A **[OK]**
 - Call `closeCallback` (from injected `BottomSheetParams`) from modal B **[OK]**
 - Call `closeCallback` (from injected `BottomSheetParams`) from modal A **[DOES NOTHING]**

**Comment by farfromrefug** [comment]
indeed for now this not possible. the solution is to close the first one before opening the second

**Comment by toverux** [comment]
Thanks for your answer.
Unfortunately, we were relying a lot on this to work as this is a kind of UX we want in different places, you can see it here, broken:

<img src="https://user-images.githubusercontent.com/1343250/111393387-f8ba5e80-86b8-11eb-8615-19d039abedbd.gif" width="50%">

Closing the first modal before won't be an option here. Is there a blocking problem that makes supporting this use case hard? Is there any possible workaround (I was thinking about the fact that it works fine with the native back button, for example)? I could also use any info on how to fix this in the library!

**Comment by farfromrefug** [comment]
@toverux I understand . I don't think material designs want you to do this ;) but anyway in really don't have time to fix it these days. you are welcome to create a PR. we would need to store the closecallback somewhere else.
PS: are you on slack? we could chat there

**Comment by toverux** [comment]
@farfromrefug You're french right? Would you agree to discuss this subject by phone (shouldn't take too long)? We would like to propose you a financial compensation if you're interested, to back this issue (and a little more). Otherwise you could also point me in the right direction. You can share your phone number with me at mtouverey@methodinthemadness.eu if you want, or I could also join you on Slack (mogolecho@hotmail.fr) if you prefer.

**Comment by toverux** [comment]
For posterity: we further discussed with @farfromrefug on Discord to find out what's the problem.
Here's a repro: https://github.com/toverux/ui-material-components-issue-250

**Comment by farfromrefug** [comment]
@toverux it would seem the issue is in the angular plugin as it works perfectly for core/vue
I see the angular module handles the `closeCallback` so i think it is responsible for "destroying".
Sadly i don't understand a thing about `angular`  :s 
If you want to take a look i would really appreciate it.
