### ISSUE TITLE
Modules documentation links ending up 404

### ISSUE THREAD

**Issue by altunyurt** [nativescript-community/ui-material-components#252]
Links to modules on documentation on https://nativescript-community.github.io/ui-material-components/ end up 404'ing.

**Comment by farfromrefug** [comment]
@altunyurt sorry about that need to fix it. BTW the doc is only generated from typings. so look at them and you ll get the same.thing

**Comment by farfromrefug** [comment]
@altunyurt docs should be good now

**Comment by altunyurt** [comment]
@farfromrefug yes all fine, thank you
