### ISSUE TITLE
dataBinding with model-view

### ISSUE THREAD

**Issue by Fabiyo-90** [nativescript-community/ui-material-components#254]
I don't know why but the dataBing with a model does not render, nothing is happening

```
let modelView = new ModelView();
let closeCallback: any;

export function onLoaded(args: any): void {
    let page: Page = <Page>args.object;
    let context = args.context;
    closeCallback = args.closeCallback;
    page.bindingContext = modelView;
}```

In my view 
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="onLoaded">
    <StackLayout>
        <Label text="message" />
        <Label text="{{message}}" />
    </StackLayout>
</Page>
```

in my model

```
import { EventData, Observable, ObservableArray } from '@nativescript/core';

interface ISex { sex: string, value: string };

export default class ModelViewSex extends Observable {
    
    private _list: ObservableArray<ISex>;

    constructor() {
        super();
        this._list = new ObservableArray([
            {sex: 'Man', value: 'h'}, {sex: 'Woman', value: 's'}
        ]);
    }

    get list(): ObservableArray<ISex> {
        return this._list;
    }

    get message(): string {
        return 'Hello world';
    }

}
```

**Comment by farfromrefug** [comment]
@Fabiyo-90 you might need  to register it in thé webpack config.  look at the vue demo for an example

**Comment by Fabiyo-90** [comment]
Let's say I gave up for an alternative solution. But we should really correct, improve the plugin on this feature

**Comment by farfromrefug** [comment]
@Fabiyo-90 i dont understand what you mean. thia plugin is working as expected for v-model. I use it all the time

**Comment by Fabiyo-90** [comment]
I don't use nativescript-vue. I use vanilla Ts.
the data that comes from a model is not displayed in the modal

**Comment by farfromrefug** [comment]
don't know how models work in N but I think it should work. must be something on webpack side or somethin

**Comment by Fabiyo-90** [comment]
I have used the model as I still use it but hey I hope there will be an improvement in this direction

**Comment by farfromrefug** [comment]
@Fabiyo-90 you are welcome to look at this. Don't forget we are doing that on our free time. Contributions are welcome

**Comment by Fabiyo-90** [comment]
I would really like to spend some time in the creation of plugins, the problem is in the nativescript community, there are a lot of patrons but very few so I do not have enough tutorials. The great advantage of nativescript is its ease of use, it is a really easy and powerful framework. But developers learn quickly through tutorials. I am looking for a clear and precise article or tutorial on how to create a plugin.
I am French and I use Google translate to communicate

**Comment by farfromrefug** [comment]
@Fabiyo-90 french too you can contact me on discord and i will guide you

**Comment by Fabiyo-90** [comment]
How to reach you on discord?

**Comment by farfromrefug** [comment]
@Fabiyo-90 get into the N discord and look for farfromrefuge#9161

**Comment by Fabiyo-90** [comment]
the message I received.
farfromrefuge#9161  does not accept friend requests. This person will have to add you in order for you to become friends.

**Comment by farfromrefug** [comment]
@Fabiyo-90 then give me your idea ;)

**Comment by Fabiyo-90** [comment]
> @ Fabiyo-90 alors donnez-moi votre idée;)

Send me an invitation to Fabiyo#4124
