### ISSUE TITLE
Missing registered elements on Angular version of tabs

### ISSUE THREAD

**Issue by patrick-nurt** [nativescript-community/ui-material-components#265]
Missing these on the angular version

registerElement('MDTabStrip', () => TabStrip);
registerElement('MDTabStripItem', () => TabStripItem);
registerElement('MDTabContentItem', () => TabContentItem);

**Comment by Bezlepkin** [comment]
https://github.com/nativescript-community/ui-material-components/pull/268/commits/05b01df7712e0c11d0716c758e3949db024df641

**Comment by farfromrefug** [comment]
@Bezlepkin actually i fixed it here https://github.com/nativescript-community/ui-material-components/commit/f0c073e844436afcf248a2d4585d03237ffa02f6

**Comment by Bezlepkin** [comment]
> @Bezlepkin actually i fixed it here [f0c073e](https://github.com/nativescript-community/ui-material-components/commit/f0c073e844436afcf248a2d4585d03237ffa02f6)

Cool!
