### ISSUE TITLE
[BottomNavigation] Usage docs are incorrect

### ISSUE THREAD

**Issue by PeterStaev** [nativescript-community/ui-material-components#269]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
The current docs for the usage of the BottomNavigation are totally messed up. 
1. The tag that should be used is NOT `<mdt:Tabs>`, but `<mdt:BottomNavigation>`
2. The `<MDTabStrip>` should be `<mdt:TabStrip>`
3. The `<MDTabStripItem>` should be `<mdt:TabStripItem>`
4. The `<MDTabContentItem>` should be `<mdt:TabContentItem>`

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?

### Please, provide the following version numbers that your issue occurs with:

- CLI:  8.0
- Cross-platform modules: 8.0.1
- Runtime(s): 8.0
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by farfromrefug** [comment]
@PeterStaev thanks for reporting this. Could you create a PR?

**Comment by PeterStaev** [comment]
@farfromrefug I can create a PR fixing only the plain NS usage since this is what I use. I'm not an NG/Vue user so not sure what should be the usage there.

**Comment by farfromrefug** [comment]
@PeterStaev that s enough for now. Thanks
