### ISSUE TITLE
[Tabs] [Angular] Swipe doesn't work

### ISSUE THREAD

**Issue by valera1401** [nativescript-community/ui-material-components#273]
### Which platform(s) does your issue occur on?
- iOS, emulator, 14.4

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.0.1
- Cross-platform modules: 8.0.0
- Runtime(s): 8.0.0
- Plugin(s): 5.2.19

Created the simple app with ns create my-tab-ng --template @nativescript/template-tab-navigation-ng
Replaced app.component.html with the following markup:
`<MDTabs>`
`  <MDTabStrip>`
     ` <MDTabStripItem>`
`          <Label text="Page 0"></Label>`
 `     </MDTabStripItem>`
     ` <MDTabStripItem>`
         ` <Label text="Page 1"></Label>`
 `     </MDTabStripItem>`
    `  <MDTabStripItem>`
        `  <Label text="Page 2"></Label>`
 `     </MDTabStripItem>`
  </MDTabStrip>

  `<MDTabContentItem>`
  `        <Label text="Page 0" class="h2 text-center"></Label>`
`</MDTabContentItem>`
`<MDTabContentItem>`
  `  <Label text="Page 1" class="h2 text-center"></Label>`
`</MDTabContentItem>`
`<MDTabContentItem>`
   `   <Label text="Page 2" class="h2 text-center"></Label>`
`</MDTabContentItem>`

Swipe doesn't work.

**Comment by farfromrefug** [comment]
@valera1401 should be fixed in latest

**Comment by valera1401** [comment]
Fixed
