### ISSUE TITLE
[Tabs] [Angular] [IOS] Tab layout is broken

### ISSUE THREAD

**Issue by valera1401** [nativescript-community/ui-material-components#279]
Which platform(s) does your issue occur on?
iOS, emulator, 14.4
Please, provide the following version numbers that your issue occurs with:
CLI: 8.0.1
Cross-platform modules: 8.0.0
Runtime(s): 8.0.0
Plugin(s): 5.2.20

https://github.com/NativeScript/NativeScript/issues/9322

**Comment by farfromrefug** [comment]
@valera1401 please try to sum up the other issue. 
Where you seeing this on N 6.x ? I mean your other issue starts by mentioning 6.5.0

**Comment by valera1401** [comment]
> @valera1401 please try to sum up the other issue.
> Where you seeing this on N 6.x ? I mean your other issue starts by mentioning 6.5.0

The issue was opened by @kenzend for the old version of the Tabs component. 
I had the same issue with old Tabs and NS 6. 
Now I'm migrating the app to the NS 8.
Replaced old Tabs with @nativescript-community/ui-material-tabs and the issue still exists.

**Comment by farfromrefug** [comment]
@valera1401 please provide a simple example to reproduce (not angular).

**Comment by valera1401** [comment]
> @valera1401 please provide a simple example to reproduce (not angular).

Yes sure. Will try to repeat it without angular.

**Comment by valera1401** [comment]
<Page xmlns="http://schemas.nativescript.org/tns.xsd" 
        xmlns:mdt="@nativescript-community/ui-material-tabs"
        navigatingTo="navigatingTo">

    <ActionBar title="My App" icon="" />

    <GridLayout>
        <mdt:Tabs 
            style="font-size: 15;" 
            selectedIndex="2">
            <mdt:TabStrip>
                <mdt:TabStripItem class="tab" title="Tab Title 1"/>
                <mdt:TabStripItem class="tab" title="Tab Title 2"/> 
                <mdt:TabStripItem class="tab" title="Tab Title 3"/> 
            </mdt:TabStrip>
            <mdt:TabContentItem>
                <GridLayout>
                    <Label text="Tab 1" />
                </GridLayout>
            </mdt:TabContentItem>
            <mdt:TabContentItem>
                <GridLayout columns="auto, auto, auto">
                    <GridLayout>
                    <Label text="Labe 1" col="0" />
                    </GridLayout>
                    <GridLayout>
                    <Label text="Labe 2" col="1" />
                    </GridLayout>
                    <GridLayout>
                    <Label text="Labe 3" col="2" />
                    </GridLayout>
                </GridLayout>
            </mdt:TabContentItem>
            <mdt:TabContentItem>
                <GridLayout>
                    <Label text="Tab 3" />
                </GridLayout>
            </mdt:TabContentItem>
        </mdt:Tabs>
    </GridLayout>
</Page>

**Comment by valera1401** [comment]
<Page xmlns="http://schemas.nativescript.org/tns.xsd" 
        xmlns:mdt="@nativescript-community/ui-material-tabs"
        navigatingTo="navigatingTo">

    <ActionBar title="My App" icon="" />

    <GridLayout>
        <mdt:Tabs 
            style="font-size: 15;" 
            selectedIndex="2">
            <mdt:TabStrip>
                <mdt:TabStripItem class="tab" title="Tab Title 1"/>
                <mdt:TabStripItem class="tab" title="Tab Title 2"/> 
                <mdt:TabStripItem class="tab" title="Tab Title 3"/> 
            </mdt:TabStrip>
            <mdt:TabContentItem>
                <Label text="Tab 1" />           
            </mdt:TabContentItem>
            <mdt:TabContentItem>
                <ScrollView>
                        <GridLayout columns="auto, auto, auto">
                            <GridLayout col="0">
                                <Label text="Labe 1" />
                            </GridLayout>
                            <GridLayout col="1" >
                                <Label text="Labe 2" />
                            </GridLayout>
                            <GridLayout col="2">
                                <Label text="Labe 3" />
                            </GridLayout>
                        </GridLayout>
                </ScrollView>
            </mdt:TabContentItem>
            <mdt:TabContentItem>
                <GridLayout>
                    <Label text="Tab 3" />
                </GridLayout>
            </mdt:TabContentItem>
        </mdt:Tabs>
    </GridLayout>
</Page>

**Comment by valera1401** [comment]
selectedIndex = 2
Tap on tab 1 

![image](https://user-images.githubusercontent.com/33029076/114915029-bd33c100-9e2b-11eb-870d-1d131a0fec9c.png)

**Comment by valera1401** [comment]
selectedIndex = 0
Tap on tab 1
![image](https://user-images.githubusercontent.com/33029076/114915176-ec4a3280-9e2b-11eb-830c-e607c770c9ec.png)

**Comment by valera1401** [comment]
Layout is broken if first navigation on Tab 1 is happening from Tab 2.
If first navigation on Tab 1 is happening from Tab 0 the layout is fine.

**Comment by farfromrefug** [comment]
@valera1401 It is working perfectly fine here. What emulator, what ios Version? What N version?
I need to know it all

**Comment by valera1401** [comment]
> @valera1401 It is working perfectly fine here. What emulator, what ios Version? What N version?
> I need to know it all

Was reproduced on the iPhone 12 emulator
IOS 14.4
NS 8.0.1
@nativescript/core 8.0.0,
@nativescript-community/ui-material-tabs 5.2.20
Xcode 12.4

Clean app created with ns create 

I will try to reproduce it on another emulator or iPhone.

**Comment by valera1401** [comment]
Checked on iPhone 11 emulator 
IOS 13.5
The same behavior

**Comment by kenzend** [comment]
@farfromrefug Could you tell me what version it works fine on? So far, I have been trying on iPhone X Preview, iPhone 8 and above emulators, but nothing works. I am wondering if this only happens on emulators and preview, but will go away after build.

**Comment by farfromrefug** [comment]
@valera1401 i think it will work for me on any version. think he issue is somewherr else. can you share your project (simple one) where it fails?

**Comment by kenzend** [comment]
Also, here is a playground link if needed: https://play.nativescript.org/?template=play-ng&id=PhTkb8&v=7
tab 0 and 1 are broken if the defaultSelected and currentTabIndex variables in home.component.ts are 2.
If the defaultSelected and currentTabIndex variables in home.component.ts are 0, tap on any tab >= 2 and tap back to 1, tab 1's layout will be broken.

**Comment by kenzend** [comment]
@farfromrefug For some context, I use the featured cradle tab bar from this NativeScript blog: https://blog.nativescript.org/tabs-and-bottomnavigation-nativescripts-two-new-components/ 
and here is the Playground from that blog: https://play.nativescript.org/?template=play-ng&id=YfZPr1
It works as provided, but after adding 2-3 layout levels, the behavior is not consistent anymore.

**Comment by valera1401** [comment]
iPhone XS MAX (not emulator)
IOS 13.6.1
NS 8.0.1
@nativescript/core 8.0.0,
@nativescript-community/ui-material-tabs 5.2.20
Xcode 12.4
Release build 

The same issue.
Tab 3 is selected by default (selectedIndex="2")
Tap on Tab 2
Layout on Tab 2 is broken

blob:https://web.whatsapp.com/6c4cd332-8b6c-40ea-abda-26e8818d5aa7

**Comment by valera1401** [comment]
[tabsjs.zip](https://github.com/nativescript-community/ui-material-components/files/6328881/tabsjs.zip)

**Comment by valera1401** [comment]
[Archive.zip](https://github.com/nativescript-community/ui-material-components/files/6328885/Archive.zip)

**Comment by farfromrefug** [comment]
@valera1401 I found the source issue. It is a `safe area` issue. by adding `iosIgnoreSafeArea="true" the scrollview gridlayout it starts working.
This is not a solution! Could you open an issue in N withe sample app, and by referencing this issue too ? Then we could look at fixing this on the N side.
Thanks

**Comment by valera1401** [comment]
Thank you very much.
Finally it's working.

Sry but I'm not sure how to describe the issue for the NS repository.
Also can't find clear documentation what is iosIgnoreSafeArea actually doing

**Comment by farfromrefug** [comment]
@valera1401 i commented on your N issue. We'll see. About the missing doc yes there is none right now because that prop should not be needed in most cases, we did not have time to document it. but it is self explanatory

**Comment by kenzend** [comment]
@farfromrefug I appreciate for your help a lot! Could you elaborate more on why this is a work around and not a solution (i.e. there could be other things go wrong after adding iosIgnoreSafeArea)?

**Comment by farfromrefug** [comment]
@kenzend workaround in the sense that it should not be needed. As for side effects i dont think there would be any. 
If you want to be sure test with an iphone 11 for example. If your layout is ok then you are good to go.
The possible side effect would be to have a wrong layout (like ignoring safe area) on devices with bottom safe area.
