### ISSUE TITLE
BottomNavigationBar fails on ios with Uncaught TypeError: Cannot read property 'isSelectable' of undefined

### ISSUE THREAD

**Issue by rayneram** [nativescript-community/ui-material-components#280]
Nativescript version: 8.0.1
Plugin version: 5.2.20
Platform: ios
Device: iPhone 7+

**Problem description:**
Basic test app using BottomNavigationBar, similar to demo. App loads up fine, but fails with the following error as soon as any of the navigation tabs are tapped:

***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'isSelectable' of undefined at
BottomNavigationBarDelegate.bottomNavigationBarShouldSelectItem(file: app/webpack:/@nativescript/template-hello-world-ts/node_modules/@nativescript-community/ui-material-bottomnavigationbar/bottomnavigationbar.ios.js:33:0)

**Observation:**
The behaviour appears to be caused by the use of the property name "tag" in the tabs within bottomnavigationbar.ios.ts. Although "tag" is set to the index correctly within createTabs(), by the time it gets referenced in bottomNavigationBarShouldSelectItem() and bottomNavigationBarDidSelectItem(), the value of "tag" has been changed (by something) so that the use of it in owner.items[tag] just produces undefined. 

I changed the name from "tag" to "index" and the code seems to work fine. It looks like something else deep in the works is using "tag". I've no idea what the side effects of simply changing the name might be, however.

**Comment by farfromrefug** [comment]
@rayneram should be fixed in latest versions. Can you test?

**Comment by rayneram** [comment]
Thanks, tested and fixed.

However, there's a minor (unrelated) issue in that /core/tab-navigation-base/tab-strip/index.ts is producing some unwated debug output in the app startup due to line 160:

`console.log('selectedItemColorProperty', value, new Error().stack);`

Probably as a result of this [commit](https://github.com/nativescript-community/ui-material-components/commit/a273379cf7379288f85e4590844e3d85ea8e41c9).

**Comment by farfromrefug** [comment]
shoot will fix !
