### ISSUE TITLE
[Tabs] [Android] Tab layout is broken after back navigation

### ISSUE THREAD

**Issue by valera1401** [nativescript-community/ui-material-components#281]
Android emulator (Pixel 4 XL API 27)
NS 8.0.1
@nativescript/core 8.0.0,
@nativescript-community/ui-material-tabs 5.2.23

1. Open SideDrawer 
2. Go to the 'Browse' page
3. Go back with the Android 'Back' button.
'Hello' label becomes black. 
It feels like new layout is drawn over the previous one. 

Attached the simple app where it can be reproduced.

[myCoolApp1.zip](https://github.com/nativescript-community/ui-material-components/files/6343590/myCoolApp1.zip)

**Comment by valera1401** [comment]
Also sometimes layout on the page with Tabs is broken, after navigating back to it with the Android 'Back' button.
For example 
Tab 4 is selected 
Navigate to some another page
Go back to the page with Tabs 
Tab 4 is selected, but broken layout from Tab 1 is displayed.

**Comment by farfromrefug** [comment]
@valera1401 your project wont build here and Angular is to heavy to debug and see where the issue actually come from.
If you can reproduce it with core or Vue then i ll fix it if it comes from this plugin

**Comment by valera1401** [comment]
Checked in js app.
The same issue. 
So it's not just Angular issue.

[myCoolApp2.zip](https://github.com/nativescript-community/ui-material-components/files/6343909/myCoolApp2.zip)

**Comment by farfromrefug** [comment]
@valera1401 it behaves correctly here. Plus you say the hello text becomes black but it is black in the first place.
I dont see anything wrong with that sample provject

**Comment by valera1401** [comment]
Run the app

![image](https://user-images.githubusercontent.com/33029076/115407639-e02dee80-a1f8-11eb-9896-245537dcc8e5.png)

Go to another page. 'Browse' for example.
Press the hardware 'Back' button.

![image](https://user-images.githubusercontent.com/33029076/115407839-0fdcf680-a1f9-11eb-8218-da0c352f1466.png)

**Comment by valera1401** [comment]
@farfromrefug  What is your Android version ?

**Comment by farfromrefug** [comment]
@valera1401 ok now i get it ! will look at it

**Comment by farfromrefug** [comment]
@valera1401 should be fixed in  5.2.24

**Comment by valera1401** [comment]
@farfromrefug Looks like it works fine now. 
Thank you very much for your help.
