### ISSUE TITLE
ui-material-bottomsheet Crashing the app while importing in app module

### ISSUE THREAD

**Issue by LakshmiEvana** [nativescript-community/ui-material-components#283]
While importing ui-material-bottomsheet in app module tns run android giving below error.

record.factory is not a function
TypeError: record.factory is not a function
    at R3Injector.hydrate (file:///data/data/org.nativescript.tempApp/files/app/vendor.js:56079:35).
    
 Can anyone help me on this please.
Below is my package.json 

{
  "name": "tempApp",
  "version": "0.0.0",
  "scripts": {
    "android": "ns run android --no-hmr",
    "ios": "ns run ios --no-hmr",
    "mobile": "ns run",
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.1.0",
    "@angular/common": "~11.1.0",
    "@angular/compiler": "~11.1.0",
    "@angular/core": "~11.1.0",
    "@angular/forms": "~11.1.0",
    "@angular/platform-browser": "~11.1.0",
    "@angular/platform-browser-dynamic": "~11.1.0",
    "@angular/router": "~11.1.0",
    "@danvick/ngx-translate-nativescript-loader": "^3.0.0",
    "@nativescript-community/ui-material-bottomnavigationbar": "^5.2.8",
    "@nativescript-community/ui-material-bottomsheet": "^5.2.8",
    "@nativescript-community/ui-material-button": "^5.2.8",
    "@nativescript-community/ui-material-floatingactionbutton": "^5.2.8",
    "@nativescript-community/ui-material-textfield": "^5.2.8",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/background-http": "^5.0.1",
    "@nativescript/camera": "^5.0.8",
    "@nativescript/core": "~7.0.0",
    "@nativescript/social-share": "^2.0.4",
    "@nativescript/theme": "~2.5.0",
    "@ngx-translate/core": "^13.0.0",
    "@nstudio/nativescript-checkbox": "^2.0.4",
    "@schematics/angular": "^9.1.8",
    "@sergeymell/nativescript-svg": "^1.0.5",
    "dayjs": "^1.10.4",
    "guid-typescript": "^1.0.9",
    "native-autocomplete": "^1.0.0",
    "nativescript-barcodescanner": "^4.0.1",
    "nativescript-carousel": "^7.0.1",
    "nativescript-fingerprint-auth": "^7.0.2",
    "nativescript-gif": "^5.0.0",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-menu": "^1.1.7",
    "nativescript-screenshot": "0.0.2",
    "nativescript-toast": "^2.0.0",
    "nativescript-ui-dataform": "^7.0.4",
    "nativescript-ui-listview": "^9.1.0",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.1",
    "@angular/cli": "~11.1.1",
    "@angular/compiler-cli": "~11.1.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/schematics": "^11.0.0",
    "@nativescript/tslint-rules": "~0.0.5",
    "@nativescript/webpack": "~3.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.2"
  },
  "main": "main.tns.js"
}

**Comment by farfromrefug** [comment]
you should in N repo, slack and discord. others had that issue they must have found a solution.
don't know anything about angular

**Comment by farfromrefug** [comment]
@LakshmiEvana it should be fixed can you confirm?

**Comment by LakshmiEvana** [comment]
Yes by removing in the module.

**Comment by farfromrefug** [comment]
@LakshmiEvana what do you mean?
