### ISSUE TITLE
MDBottomNavigation: How to get the current selected index?

### ISSUE THREAD

**Issue by sowinski** [nativescript-community/ui-material-components#289]
Hi,

how can I get the current selected index? 

This is what I tried so far:
```
    <MDBottomNavigation
      :selectedIndex="selectedIndex"
      @selectedIndexChanged="selectionChanged"
    >

...

export default {
  data() {
    return {
      selectedIndex: 0,
    };
  },
  methods: {
    selectionChanged(event) {
      console.log("change selection");
      console.log(this.selectedIndex);
    },
  },
};
```

Selected index is always 0. The event is fired correctly. Not sure if this is a bug or I do it the wrong way.

**Comment by farfromrefug** [comment]
@sowinski what you do wont update the selectedIndex prop. This is not a component problem. It is  an issue with understanding how vue works. Either use `v-model` or in your `selectionChanged` set `this.selectedIndex = event.value`
