### ISSUE TITLE
ui-material-bottomsheet doesn't work after a promise or observable

### ISSUE THREAD

**Issue by Bezlepkin** [nativescript-community/ui-material-components#297]
Hi! I try to open the ui-material-bottomsheet after calling Http (observable).

The component opens but with errors. The ngOnInit method does not work, only the constructor. If you call immediately, without a promise and observable, then everything works correctly

NativeScript: 8.0.1
Android: 9
ui-material-bottomsheet: 5.2.13

**Comment by farfromrefug** [comment]
@Bezlepkin you are gonna have to give more info that this. You say errors but you dont even put the errors here.
Feels like an angular zone thing issue. But dont know anything about angular.

**Comment by Bezlepkin** [comment]
figured it out. This only works if the promise is via then.
If via async await it doesn't work.
