### ISSUE TITLE
SpeedDial Font Icon / Material doesnt work with Vue

### ISSUE THREAD

**Issue by pitw** [nativescript-community/ui-material-components#298]
Using NS8  with vue-nativescript and latests plugins I'm not able to get icons working for Speed Dial.

Looks like this:

![image](https://user-images.githubusercontent.com/5676857/118512778-66275180-b733-11eb-9e87-21348b22a3dd.png)

Code:

`  <MDSpeedDial text="mdi-one-up" buttonClass="mdi">
        <MDSpeedDialItem
          icon="res://ic_action_add"
          title="test1"
          backgroundColor="red"
          @tap="onTap"
        />
        <MDSpeedDialItem
          text="mdi-card-account-mail"
          title="test2"
          buttonClass="mdi"
          backgroundColor="green"
          @tap="onTap"
        />
        <MDSpeedDialItem
          backgroundImage="~/images/iu.jpg"
          backgroundColor="blue"
          @tap="onTap"
        />
        <MDSpeedDialItem
          icon="res://ic_action_add"
          title="test4"
          backgroundColor="orange"
          @tap="onTap"
        />
      </MDSpeedDial>`

Material Icons are working on standard buttons or on other components (f.ex. RadListView)

I also compared with demo - there you have a custom [**app.webpack.config.js**](https://github.com/nativescript-community/ui-material-components/blob/bd6d3511757caf8a189ea05848ae8f88cc20d5b8/demo-vue/app.webpack.config.js#L126) which seems to replace icons.
Tried also with that but doesnt seem to work either...

Is the fix with custom **app.webpack.config.js** necessary or should it work with default nativescript font-icon integration ?

I also created a test repo (Android) which this behaviour: https://github.com/pitw/nativescript-material-speeddial-test

**Comment by farfromrefug** [comment]
@pitw i might try your test repo but dont have that much time right now.
Does it work if you set class mdi through css?
does the demo work for you?

**Comment by pitw** [comment]
I installed latest demo (Vue, Android) from your repo. 
The speed dial sample doesnt seem to work (clicking -> no result, stays in main menu)

But the buttons demo shows similar error like I have above:

![image](https://user-images.githubusercontent.com/5676857/118525878-f2d80c80-b73f-11eb-9116-a1cd75afb368.png)

(The only button you use in demo with "mdi" doenst show up in demo - both marked red)

**Comment by zamblas** [comment]
Try using unicode, I'm using:
 
` <MDSpeedDialItem
     backgroundColor="white"
     buttonClass="btn-rnd"
     color="#f15a29"
     text.decode="&#xe2c7;"
     @tap="newFolder"
/>`

`.btn-rnd {
  font-family: "MaterialIcons-Regular", "Material Icons" ;
  height: 40;
  width: 40;
  border-radius: 20;
  background-color: #f15a29;
}`

**Comment by pitw** [comment]
Thanks - but doesnt work. With unicode I get this:
![image](https://user-images.githubusercontent.com/5676857/121134314-8d090d00-c833-11eb-843d-ae65c10790d4.png)

@zamblas: Are you using latest NS (8.0.7) and latest SpeedDial (5.3.3) ?

**Comment by farfromrefug** [comment]
are you sûre your gets picked up ?

**Comment by pitw** [comment]
Updated, Rebuilt, Cleaned 3-times. Now it works ;)

I updated also my test repo with comments from @zamblas; in case sb has same problem - there's a code example with context: https://github.com/pitw/nativescript-material-speeddial-test/blob/ffb644a2f80a556f0070d6f63b7fe1da12113134/app/components/Home.vue#L11
