### ISSUE TITLE
Feature request for easier bug reporting 

### ISSUE THREAD

**Issue by sowinski** [nativescript-community/ui-material-components#299]
Hi,

I found a tab bug on iOS systems and would like to share it on nativescript playground. (So it will be easier and faster for everyone to see or reproduce an error).

Unfortunately I don't know how to add your library to the playground here? https://play.nativescript.org/

Can someone help? :)

**Comment by farfromrefug** [comment]
@sowinski dont think you can do that. You should ask on discord about the playground
