### ISSUE TITLE
Not able to use appium with MDTextFields

### ISSUE THREAD

**Issue by ruminder-hub** [nativescript-community/ui-material-components#304]
### Which platform(s) does your issue occur on?
- Android
- Android version: Any

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.8.0
- "tns-android": {
      "version": "6.4.1"
    }
- Plugin(s): "nativescript-material-textfield": "3.1.9",

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
Install dependencies: nativescript-material-textfield dependency, nativescript-dev-appium, wd
Add to the login form with a property of automationText.
**<MDTextField hint="Enter Username" keyboardType="email"
            autocorrect="false" 
            class="input input-border"  automationText="username">
</MDTextField>**

Install appium server application
To capture the code of the application you can follow this [link](https://ruminder-singh.medium.com/using-appium-with-nativescript-53bf71b316c)

The problem is automationText property is not set at the editText level, it is created at a different level of UI hierarchy.

<img width="324" alt="Screen Shot 2021-05-31 at 4 27 51 PM" src="https://user-images.githubusercontent.com/65379043/120233943-490f7a00-c22d-11eb-9748-fe2d56351945.png">

On writing automation test cases for the application, it gets failed as the automationText property is not able to identify the field.
it("loginCheck", async function () {
        let el1 = await driver.findElementByAutomationText("Username");
        await el1.click();
        await el1.sendKeys("andre");

        assert(el1.text(), "andre");
    });

**Comment by farfromrefug** [comment]
@ruminder-hub this is an issue with N which does not set it on `nativeTextViewProtected` but `nativeViewProtected` instead.

**Comment by chuckmitchell** [comment]
Here is an interesting comment which seems to reference exactly what we're talking about.
However I don't know how to "override the `nativeTextViewProtected` getter" as suggested.

Is this possible in the plugin code? @farfromrefug  Am I on the right track?

https://github.com/NativeScript/NativeScript/pull/8886/commits/56b7a80de3abc6b0d29a358352cee039e3bf5869

**Comment by farfromrefug** [comment]
@chuckmitchell created a PR https://github.com/NativeScript/NativeScript/pull/9432
