### ISSUE TITLE
[bottomSheet] [iOS] ListView Brokes safeArea

### ISSUE THREAD

**Issue by Hugo-Dlg** [nativescript-community/ui-material-components#305]
Hello, I use BottomSheet to display a list of country with a listView my issue is about the height, if I don't set any height, it takes the fullscreen except the top : 
![image](https://user-images.githubusercontent.com/80692737/120251600-56a31f00-c282-11eb-9502-4aeac2b5470f.png)
If i put the phone on landscape I got a big white part : 
![image](https://user-images.githubusercontent.com/80692737/120251653-88b48100-c282-11eb-8e57-9f55f72d2ee7.png)

To fix the fullscreen I need to set an height in my listView butit puts a safeArea under my BottomSheet, I would like to be able to set a background color on it : 
![image](https://user-images.githubusercontent.com/80692737/120251787-e648cd80-c282-11eb-90a8-bc7f79db37df.png)

And on Landscape mode, I have both safe area and white part : 
![image](https://user-images.githubusercontent.com/80692737/120251813-feb8e800-c282-11eb-9578-715fe19c5b95.png)

This issue is only happening with BottomSheet on iOS and also if you've a solution to be able to don't set any height and just get it dynamically like Android

### Which platform(s) does your issue occur on?
- emulator Iphone 12 iOS 14.5

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.0.2
- Cross-platform modules: 8.0.6
- Runtime(s): 8.0.0
- Plugin(s): "@nativescript-community/ui-material-bottomsheet": "^5.3.0",

### Please, tell us how to recreate the issue in as much detail as possible. 
Put a list view inside a bottomsheet and switch to landscape mode or set a height to the listview

### Is there any code involved? 
Here's the code for the bottomSheet : 
```js
<StackLayout style="background-color: red">
	<TextField hint="Edit text to filter..." [(ngModel)]="filterItem" (ngModelChange)="filterLongList()" style="font-size: 16;"></TextField>
	<ActivityIndicator *ngIf="processing" [busy]="processing" width="50" height="50"></ActivityIndicator>
	<ListView height="150" #listview [items]="items" (itemTap)="onItemTap($event)">
		<ng-template let-item="item" let-odd="odd" let-even="even">
			<GridLayout height="64">
				<Image horizontalAlignment="left" width="64" [src]="item.flag"></Image>
				<Label horizontalAlignment="center" [text]="item.name" ></Label>
				<Label horizontalAlignment="right" [text]="item.dialCode"></Label>
			</GridLayout>
		</ng-template>
	</ListView>
	<Button text="Cancel" horizontalAlignment="center" (tap)="cancel()"></Button>
</StackLayout>
```
Feel free if you've any other question. I also tried with iosOverflowSafeArea="true" on my stackLayout but not changing anything.

Thanks 

**Edit :**
I tried to look with an iPad and I can see both white part  :
![image](https://user-images.githubusercontent.com/80692737/120252276-573cb500-c284-11eb-815d-8ad7c66e1f21.png)
If it can give you an idea

**Comment by farfromrefug** [comment]
@Hugo-Dlg i fixed it in 5.3.3. However it is not perfect yet. I cant seem to find a way to "ignore" left/right safe area inset in landscaepe mode

**Comment by Hugo-Dlg** [comment]
If I remove margin it's a little better : 
![image](https://user-images.githubusercontent.com/80692737/120300266-1072ad80-c2cc-11eb-8066-a58a25ac71ae.png)
![image](https://user-images.githubusercontent.com/80692737/120300346-21bbba00-c2cc-11eb-9cc2-a6248a9c8bff.png)

Do you have any idea about setting the color of the safeArea ?

**Comment by farfromrefug** [comment]
@Hugo-Dlg for now the only solution is to use the `transparent` option. Would need to look at setting a custom background color.

**Comment by Hugo-Dlg** [comment]
Ok thanks I'll take a look at it
