### ISSUE TITLE
bottomsheet add a position. slightly slightly ajar (100 dp) approximately.

### ISSUE THREAD

**Issue by Bezlepkin** [nativescript-community/ui-material-components#306]
Now the bottomsheet opens approximately in the middle of the screen. When you swipe down, it closes. Is it possible to add another position, approximately 100 meters high. That is, what would have turned out to be three positions: in the middle, full screen, and a slightly open position.

- Android 
- Android 9
- Device

**Comment by farfromrefug** [comment]
@Bezlepkin i dont understand what you are talking about?
Please give more information when you open an issue.

**Comment by Bezlepkin** [comment]
So that you can open it:
- full screen (as currently implemented)
- in the middle of the screen (as already implemented)
- to open a little bit (as in the video)

![ezgif-7-b438f4a0116b](https://user-images.githubusercontent.com/10475699/121167441-9bb6ea80-c85a-11eb-8d72-35c24c32d594.gif)

**Comment by farfromrefug** [comment]
@Bezlepkin seems nice. I wont implement it until i need it. Sorry a lot to do / maintain. But if you want to have a go at it would love to have a PR :D

**Comment by Bezlepkin** [comment]
> @Bezlepkin seems nice. I wont implement it until i need it. Sorry a lot to do / maintain. But if you want to have a go at it would love to have a PR :D

I would love to! But where to start? :)

**Comment by farfromrefug** [comment]
@Bezlepkin first look at the native APIs to see how they handle it. Then try to find an API which would work for bot platforms then implement and test it

**Comment by Bezlepkin** [comment]
> first look at the native APIs to see how they handle it. Then try to find an API which would work for bot platforms then implement and test it

For this implementation, you do not need to add code to Java Android?

**Comment by farfromrefug** [comment]
@Bezlepkin there is no java code. It is all handled from the JS side (but still calling java code)

**Comment by vallemar** [comment]
I have been interested in this behavior, in android it is very easy since it lets you indicate at the height that you want to open the bottomshet, in iOS I have no idea but I will try to take some time to investigate as well

**Comment by vallemar** [comment]
@Bezlepkin I have it working in android but in ios I don't get it. have you been able to see any of this?

**Comment by Bezlepkin** [comment]
> I have it working in android but in ios I don't get it. have you been able to see any of this?

No! How are you do it for Android?

**Comment by vallemar** [comment]
Sorry @Bezlepkin, here you can see how to add this functionality only for android, the other options are not checked, only the default height that the developer wants. [Repo](https://github.com/vallemar/ui-material-components/commit/24a60d9a2c3f5720d543847479e3cbbe71e62de2)

**Comment by vallemar** [comment]
@farfromrefug I have been able to add this functionality for android [here](https://github.com/vallemar/ui-material-components/commit/b39577f274b76b15b9e33cebca3c45addb2d93a7), but for ios it does not work: [here](https://github.com/vallemar/ui-material-components/commit/e8d695b7200d2884a47eac626372dd50098211a6). According to the [documentation ](https://github.com/material-components/material-components-ios/tree/develop/components/BottomSheet#sheet-properties)it should do that, I suspect that it is related to this [method ](https://github.com/vallemar/ui-material-components/blob/master/src/bottomsheet/bottomsheet.ios.ts#L64)but I would not know how to do it. Do you know a "quick" way to implement this?

**Comment by farfromrefug** [comment]
@vallemar not sure you can use the property to set it in N on iOS. Try to use `setPrefered...`
Also if you make a PR i am not sure about the name `collapsedHeight` i would prefer we use the name used on iOS or android

**Comment by vallemar** [comment]
> Además, si hace un PR, no estoy seguro del nombre `collapsedHeight`, preferiría que usemos el nombre que se usa en iOS o Android

Perfect, I would stick with the iOS one. I will not do the PR until I find a solution for iOS. Thanks! @Bezlepkin Have you been able to take a look at this?

**Comment by farfromrefug** [comment]
@Bezlepkin @vallemar just released 6.0.2 with support for `peekHeight` on iOS/Android. Thanks @vallemar for your PR!

**Comment by vallemar** [comment]
@Bezlepkin can you close this issue?
