### ISSUE TITLE
[bottomsheet] The bottom sheet doesn't work after upgrading to Angular 12

### ISSUE THREAD

**Issue by Bezlepkin** [nativescript-community/ui-material-components#307]
After updating to Angular 12 bottomsheet throws an error.

**ERROR Error: Uncaught (in promise): TypeError: Right-hand side of 'instanceof' is not an object**

- NativeScript 8 + Angular 12
- Android Device

I looked into the code and saw that there is no AppHostView in Angular 12
![2021-06-09_14-13-33](https://user-images.githubusercontent.com/10475699/121344893-e86af600-c92c-11eb-8ba2-7993d3a7479e.png)

**Comment by edusperoni** [comment]
This is fixed in: https://github.com/NativeScript/angular/commit/601b080de38eff91b5e40aed44fbb9782d08c05a

**Comment by Hugo-Dlg** [comment]
Is it a client side modification or dev side ?

**Comment by Bezlepkin** [comment]
> Is it a client side modification or dev side ?

What you mean?

**Comment by Hugo-Dlg** [comment]
I was wondering if we had to do the modification as a user in our program or if it had to be done by the package developer, but I found the answer after thinking about it

**Comment by Bezlepkin** [comment]
> I was wondering if we had to do the modification as a user in our program or if it had to be done by the package developer, but I found the answer after thinking about it

I made a package in node_modules but nothing has changed. Apparently we need to wait for @nativescript/angular 12.0.2

**Comment by edusperoni** [comment]
@nativescript/angular@12.0.2 has been released today. Please update and test it! I think this issue can be closed

**Comment by Bezlepkin** [comment]
I get new error:

JS: ERROR TypeError: Cannot read property '0' of null

I checked the code, I suspect that an error occurs when calling this method:
![2021-06-18_09-37-34](https://user-images.githubusercontent.com/10475699/122517575-de29b580-d018-11eb-9f1d-48dedd40ee99.png)

**Comment by farfromrefug** [comment]
@Bezlepkin @edusperoni cant say much about angular. Would need some help to fix this.
