### ISSUE TITLE
Tabs iOS: TabContent is overlapping custom tab strip

### ISSUE THREAD

**Issue by felixkrautschuk** [nativescript-community/ui-material-components#320]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

In one of our pages we want to use the Tabs component with a custom tab strip, as we need some complex layout with badges etc which is not supported by the default TabStrip component of this plugin.
So we wanted to do something similar being described at the end of this blog post, where the new Tabs component has been announced for NS 6: [https://blog.nativescript.org/tabs-and-bottomnavigation-nativescripts-two-new-components/](https://blog.nativescript.org/tabs-and-bottomnavigation-nativescripts-two-new-components/)

So we tried to ommit the TabStrip at all and put a custom TabStrip above within a GridLayout.

```
<GridLayout rows="50,*">
        <GridLayout row="0" height="50" rows="*" columns="*,*,*,*,*">
            <!--  custom tab buttons  -->
        </GridLayout>

        <mdt:Tabs row="1" selectedIndex="{{ selectedTabIndex }}" tabsPosition="top">
            <mdt:TabContentItem>
                <GridLayout>
                    <Label text="Tab 1" class="center"/>
                </GridLayout>
            </mdt:TabContentItem>
            <mdt:TabContentItem>
                <!--  ...  -->
            </mdt:TabContentItem>
        </mdt:Tabs>
</GridLayout>
```

It works as expected, but unfortunately, on iOS the custom TabStrip is overlapped by the TabContentItems.

<img width="876" alt="Bildschirmfoto 2021-07-30 um 10 44 13" src="https://user-images.githubusercontent.com/6443021/127627062-4823c42d-c65b-4cd9-a2c1-192778c9af4e.png">

When I define a background-color for TabContentItem in CSS, the custom TabStrip is not visible at all on iOS.

I have tried to set a marginTop to the Tabs element, to the TabContentItems etc, but this has no effect.

When setting some marginTop to the view within TabContentItem:
```
<mdt:TabContentItem>
    <GridLayout marginTop="70">
        <!-- ... -->
    </GridLayout>
</mdt:TabContentItem>
```
... then the content does not visually overlap the custom tabstrip, but the user is still not able to interact with the tabs (tapping not possible).

### Which platform(s) does your issue occur on?
- iOS
- iOS 12, 13, 14
- emulator or device ? -> both

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.0.2
- Cross-platform modules: 8.0.8
- Runtime(s): 8.0.0
- Plugin(s): nativescript-community/ui-material-tabs 5.3.11

### Please, tell us how to recreate the issue in as much detail as possible. 
Run the demo app provided below, switch to the second tab.

### Is there any code involved? 
[ns-custom-tabs.zip](https://github.com/nativescript-community/ui-material-components/files/6906215/ns-custom-tabs.zip)

**Comment by felixkrautschuk** [comment]
I found a workaround:

One needs to add the Tabs component and the custom tabstrip element at the same herarchical level within a GridLayout:

```
<GridLayout>
        <mdt:Tabs selectedIndex="{{ selectedTabIndex }}">
            <mdt:TabContentItem>
                ...
            </mdt:TabContentItem>
            <mdt:TabContentItem>
                ...
            </mdt:TabContentItem>
            ...
        </mdt:Tabs>

        <GridLayout rows="*" columns="*,*,*,*,*" className="tabstrip-custom">
            ...
        </GridLayout>
</GridLayout>
```

The custom tabstrip needs to be vertically aligned via css

```
.tabstrip-custom {
    height: 70;
    vertical-align: top;
}
```


The Tabs component needs to get a margin-top with the height of the custom tabstrip

```
MDTabs {
    margin-top: 70;
}
```


Now on iOS, the custom TabStrip is still overlapping the TabContentItem. The TabContentItem has no option to set a margin or a padding on top, but this can be added to any direct child like this:

```
.ns-ios MDTabContentItem > * {
    padding-top: 70;
}
```

**Comment by farfromrefug** [comment]
@felixkrautschuk sorry for answering so late. I actually implemented this for bottom-navigation with `iosCustomPositioning` property. Just published a new version which allows it too with `Tabs`

**Comment by felixkrautschuk** [comment]
@farfromrefug ah perfect! thanks!
