### ISSUE TITLE
Bottom navigation bar - Router Outlet

### ISSUE THREAD

**Issue by csimpi** [nativescript-community/ui-material-components#323]
I have the most recent version of everything.

Unfortunately, it seems the demo doesn't compatible with `page-router-outlet`. The demo uses `ngSwitch` to switch between tabs. It seems `ngSwitch` doesn't work with `page-router-outlet`. When I change a tab and change back the content disappears. I guess this is by Angular. I remember there're similar issues with `ngIf` before.

Based on these I think there are two ways to handle this:
- Change the demo to something that works with `page-router-outlet` (for example using hidden attribute)
- Make `page-router-outlet` work with `ngSwitch`

**Comment by farfromrefug** [comment]
@csimpi dont know much about angular. You are welcome to make a PR

**Comment by csimpi** [comment]
@farfromrefug Are you kidding? As I know this supposed to be the "official" NS UI plugin as a replacement the deprecated core elements and you are just ignoring Angular? Also your answers seems to be rude, like you are angry because I asked about Angular. Angular is an essential part of NS and as I see on the channel it is going to be more and more popular. 

Please, support Angular or don't say this is going to be the replacement of the core UI elements. I upgraded to NS8 but it seems NOTHING is supported, the whole project is collapsing

**Comment by farfromrefug** [comment]
@csimpi where did you see it was an official N plugin :D well, what wait... am i paid for this?

Thank you for you kindness. have a great day

**Comment by csimpi** [comment]
@farfromrefug You are super rude man, this is not a community plugin, it seems you are the only one here, and nobody participate anymore. I guess why, cause I wanted to contribute if necessary but not anymore. Your communication skills are super low.

Here is your answer:

> Important note about BottomNavigation and Tabs
> BottomNavigation and Tabs ui components in core brought along Cocoapods whether your project used them or not. With 8.0, they now are provided by the community where **### they can receive more focused attention** not bound or held up by NativeScript core updates.

**Comment by farfromrefug** [comment]
@csimpi stop saying i am rude, read yourself! I agreed to took over those components from the N core project. And YES it IS a community project. I am mostly the only one here because i created that repo from the start and did it all. 
There is no one else mostly because everyone is like you, simply ungrateful for what other do for you out of kindness and trust for OSS.
I am done talking here. If you are unhappy move your "rude" discussions on discord

**Comment by csimpi** [comment]
@farfromrefug Repeating OSS project won't justify that, BottomNavigation worked perfectly before now you ruined it. Why did you even touch it if it worked well? Everybody with {N} + Angular upgrading to 8 is over? not supported? job is done? 
congrats then for your awesome COmMuNitY

**Comment by farfromrefug** [comment]
@juniorschen please such comment have no place on github. It is a place to report issues. Not to give opinions or swear ...
I will hide your comment because of this.

**Comment by Salahudeen** [comment]
@csimpi @vallemar Were you able to find any resolution to this issue? if so, can you guide me on the same?

**Comment by vallemar** [comment]
@Salahudeen Could you make a sample repository? I think I could take a look but I don't really know what's going on

**Comment by Salahudeen** [comment]
@vallemar Thanks for the quick response. I made the below repo with the details. Please run on iOS
https://github.com/Salahudeen/ui-material-bottomnavigationbar-issue

Objective is to lazy load modules on each tab load like in the example ns create new => Tab sample app.
