### ISSUE TITLE
ui-material-tabs break on back navigation (ios)

### ISSUE THREAD

**Issue by cjohn001** [nativescript-community/ui-material-components#339]
### Which platform(s) does your issue occur on?
- iOS 15

### Please, provide the following version numbers that your issue occurs with:
- CLI:8.1.4
- Cross-platform modules:  "@nativescript/core": "8.1.5",
- Runtime(s): JSC (Update: I removed the new runtime, seems like I had forgotten to do a clean, only seems to appear with JSC)
- Plugin(s): "@nativescript-community/ui-material-tabs": "~6.2.2", I tried down to 5.x versions, same problem with older packages as well. I suspect it to be related to IOS 15, IOS 11 on emulator does not show the problem

### Please, tell us how to recreate the issue in as much detail as possible. 
As can be seen in the attached video, when transitioning back to the view, the top tabbar is shifted by a certain amount into the page. Could have to do with OverflowSaveArea?

Forward/Backword navigation with vertical slide transition is responsible for the bug to show up, other page transitions do not lead to this error

https://user-images.githubusercontent.com/43253483/139599962-45c453cd-12a8-412f-b1c8-febfa60fa942.mov

	<MDTabs animationEnabled="false" offscreenTabLimit="4" swipeEnabled="false" [selectedIndex]="_selectedIndex"
			(selectedIndexChanged)="onSelectedIndexChanged($event)" class="border-top">
			<MDTabStrip>
				<MDTabStripItem>
					<Label text="{{ 'selection.strSearch' | L }}" class="tabStripLabel"></Label>
				</MDTabStripItem>

				<MDTabStripItem>
					<Label text="{{ 'selection.strCustom' | L }}" class="tabStripLabel"></Label>
				</MDTabStripItem>

				<MDTabStripItem>
					<Label text="{{ 'selection.strMeals' | L }}" class="tabStripLabel"></Label>
				</MDTabStripItem>

				<MDTabStripItem>
					<Label text="{{ 'selection.strQuick' | L }}" class="tabStripLabel"></Label>
				</MDTabStripItem>
			</MDTabStrip>

			<MDTabContentItem>
				<ContentView>
					<ns-search-tab *ngIf="_showSearchTab"></ns-search-tab>
				</ContentView>
			</MDTabContentItem>

			<MDTabContentItem>
				<ContentView>
					<ns-custom-tab *ngIf="_showCustomTab"></ns-custom-tab>
				</ContentView>
			</MDTabContentItem>

			<MDTabContentItem>
				<ContentView>
					<ns-meals-tab *ngIf="_showMealsTab"></ns-meals-tab>
				</ContentView>
			</MDTabContentItem>

			<MDTabContentItem>
				<ContentView>
					<ns-quickly-add-tab *ngIf="_showQuicklyAddTab"></ns-quickly-add-tab>
				</ContentView>
			</MDTabContentItem>
		</MDTabs>

**Comment by farfromrefug** [comment]
@cjohn001 would be good to try and replicate that issue with N core version (no plugin). It could help pinpoint where the issue comes from

**Comment by cjohn001** [comment]
@farfromrefug. I do not know how to work with N core, only Angular.

**Comment by farfromrefug** [comment]
@cjohn001 you can use `ns create` to create a simple example on which you can try and replicate the issue. It is essential to be able to pinpoint the issue

**Comment by cjohn001** [comment]
Well I currently do not have the time to look into it. I need to see how to find a workaround the problem first.

**Comment by cjohn001** [comment]
@farfromrefug : I will close the issue as there seems to be black magic happening (behavior was 100% repeatable yesterday). 
I have rebuild the app this morning and cannot see the reported behavior anymore. As all packages are in the same version like they were yesterday and I made no code changes, I do not understand whats happening. I think it makes no sense to debug something which is not repeatable, therefore I close the issue
