### ISSUE TITLE
Can't apply styling to MDBottomNavigation via CSS

### ISSUE THREAD

**Issue by BikeBr0** [nativescript-community/ui-material-components#342]
I've copied the markup for angular from: https://market.nativescript.org/plugins/@nativescript-community/ui-material-bottom-navigation/ into my app.component.html file and the MDBottomNavigation component works. However, any styling I try to apply to it from app.css does not take effect (it works for MDButton and MDTextField). Adding style directly on the MDBottomNavigation tag does work but applying "tabstripitem-active" style is eluding me. I suspect this is a user error or perhaps a problem with the documentation. Any advice? I'm running NativeScript 8.1.4 and testing on Android 8.1.0

From package.json
    "@angular/animations": "~12.0.0",
    "@angular/common": "~12.0.0",
    "@angular/compiler": "~12.0.0",
    "@angular/core": "~12.0.0",
    "@angular/forms": "~12.0.0",
    "@angular/platform-browser": "~12.0.0",
    "@angular/platform-browser-dynamic": "~12.0.0",
    "@angular/router": "~12.0.0",
    "@nativescript-community/ble": "^3.0.29",
    "@nativescript-community/insomnia": "^2.0.2",
    "@nativescript-community/ui-material-bottom-uinavigation": "^6.2.2",
    "@nativescript-community/ui-material-button": "^6.2.2",
    "@nativescript-community/ui-material-textfield": "^6.2.2",
    "@nativescript-community/ui-pulltorefresh": "^2.4.8",
    "@nativescript/angular": "~12.2.0",
    "@nativescript/core": "~8.1.2",
    "@nativescript/theme": "~3.0.1",
    "nativescript-clipboard": "^2.1.1",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.4"

**Comment by BikeBr0** [comment]
To be clear, this fails:

app.css
MDBottomNavigation {
    background-color: #d9e1e1;
}

while this works:

app.component.html
<MDBottomNavigation selectedIndex="0" style="backgroundColor: #d9e1e1;">

**Comment by farfromrefug** [comment]
@BikeBr0 you need to use `BottomNavigation` in CSS. it is bug. Though it is  hard to fix because if i change to `MDBottomNavigation` then it would break for people using `BottomNavigation`
I just updated the doc.
Can you close this issue if this fixes it for you?

**Comment by BikeBr0** [comment]
Thanks for getting back to @farfromrefug . I just tried:

```
BottomNavigation {
    background-color: #d9e1e1;
}
```

But it did not work

**Comment by farfromrefug** [comment]
@BikeBr0 actually found out that you need to set the bar background color with `MDTabStrip` and not `BottomNavigation`. `BottomNavigation` applies to the whole component

**Comment by BikeBr0** [comment]
Correct, but I _was_ actually trying to apply a background color to the whole component (and then style the TabStrip seperately). I still think this is an issue but I have switched to the BottomNavigationBar component instead as it was easy to get badge support working.
