### ISSUE TITLE
MDTabs force fixed layout

### ISSUE THREAD

**Issue by mrzanirato** [nativescript-community/ui-material-components#360]
Hello,

I need help with MDTabs ( NS 8 )

If I add more than 4 tabs the layout change in scollable instead of fixed.

How can I force the fixed layout?

Thanks

Marco

![Simulator Screen Shot - iPhone 13 - 2022-02-22 at 17 00 33](https://user-images.githubusercontent.com/61496516/155170627-6ced6a18-6661-490e-8290-50a12b8ca3b5.png)

**Comment by farfromrefug** [comment]
@mrzanirato this is how it always have been. Sorry but this wont change. you can try https://github.com/nativescript-community/ui-material-components/blob/master/packages/bottomnavigationbar/README.md

**Comment by mrzanirato** [comment]
ok thanks.
I tried bottomnavigationbar but I don't know how to use page-router-outlet
Can you help?
Thanks

**Comment by farfromrefug** [comment]
@mrzanirato sorry idont know anything about angular.

**Comment by mrzanirato** [comment]
ok no problem, thanks
