### ISSUE TITLE
Failed to build plugin @nativescript-community/ui-material-core

### ISSUE THREAD

**Issue by pkowalezyk** [nativescript-community/ui-material-components#369]
Hello,

When trying to launch my project with  "ns run android --emulator", I get the following error : 

> FAILURE: Build failed with an exception.
> 
> Build file '.\platforms\tempPlugin\ui_material_core\build.gradle' line: 108
> 
> * What went wrong:
> A problem occurred evaluating root project 'ui_material_core'.
> > Could not find method compile() for arguments [androidx.appcompat:appcompat:1.2.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> Failed to build plugin @nativescript-community/ui-material-core :
> Error: Command gradlew.bat failed with exit code 1

I recently cleared my npm cache, I didn't have the problem before. Could it be linked ?

Thank you.

**Comment by farfromrefug** [comment]
@pkowalezyk what version of the plugin are you using ? we are not using `compile` anymore as it is not supported by gradle 7

**Comment by pkowalezyk** [comment]
I'm using the 5.3.0 version of the plugin

**Comment by farfromrefug** [comment]
@pkowalezyk we are at 7.x ;)

**Comment by pkowalezyk** [comment]
It seems that this issue is linked to recent Nativescript dependencies changes.
I solved my issue by updating NativeScript (from 8.01 to 8.2.2).

**Comment by liamcharmer** [comment]
I have updated the Nativescript (by running ns update). 

i now have this issue:

```
Build file '/Users/liamcharmer/Projects/TraxApp/platforms/tempPlugin/ui_material_core/build.gradle' line: 140

* What went wrong:
A problem occurred evaluating root project 'ui_material_core'.
> Could not find method compile() for arguments [androidx.appcompat:appcompat:1.2.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

```

**Comment by farfromrefug** [comment]
@liamcharmer look at the comment. It is a setup/clean issue
