### ISSUE TITLE
Tabs 6.2.21+: swiping feels jerky with RadListViews

### ISSUE THREAD

**Issue by felixkrautschuk** [nativescript-community/ui-material-components#375]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

We just migrated the @nativescript-community/ui-material-tabs from 6.2.19 to 7.0.2 in one of our production apps and we notice that the swiping of the Tabs feels jerky, at least on physical devices.
I used a Google Pixel 3a for testing. It's not the newest device, but it's not ancient either and I do not notice this issue when just switching back to 6.2.19.

In the sample app provided below, the issue is reproducable on physical devices. However, the issue is more noticable in our production app, where we use more complex layouts in the page and especially for the list item templates.

### Which platform(s) does your issue occur on?
- Android (not tested iOS yet)
- multiple Android versions
- only reproducable on physical device (e.g. Google Pixel 3a)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.1.5
- Cross-platform modules: 8.2.1
- Runtime(s): 8.2.2
- Plugin(s): 7.0.2

### Please, tell us how to recreate the issue in as much detail as possible. 
- Start the sample app (provided below) on a physical device.
- Swipe (slowly) between the tabs with RadListViews -> it is "hanging" a bit

### Is there any code involved? 
[ns-custom-tabs.zip](https://github.com/nativescript-community/ui-material-components/files/8361347/ns-custom-tabs.zip)

**Comment by farfromrefug** [comment]
@felixkrautschuk this comes from the fact that your tab takes too long to "load" itself. 
You should offload the loading of the content to the "loaded" event or even better once the tab is actually shown. 
This is a know thing on all platforms.
You might not have seen this before because all tabs were loaded on start (which is wrong).
You can also change the `offscreenTabLimit` to a higher value. But this is not a fix! This is a workaround for something that should be fixed in your app

**Comment by felixkrautschuk** [comment]
@farfromrefug Maybe I'm misunderstanding you or the sense of the _offscreenTabLimit_ property.

I have added a loaded and unloaded event handler for the GridLayout inside TabContent for better tracking what is happening, so the app looks like this:

```
<mdt:Tabs>
            <mdt:TabContentItem>
                <GridLayout id="tab0" loaded="onTabContentLoaded" unloaded="onTabContentUnloaded">
                    ...
                </GridLayout>
            </mdt:TabContentItem>
            <mdt:TabContentItem>
                <GridLayout id="tab1" loaded="onTabContentLoaded" unloaded="onTabContentUnloaded">
                    ...
                </GridLayout>
            </mdt:TabContentItem>
            <mdt:TabContentItem>
                <GridLayout id="tab2" loaded="onTabContentLoaded" unloaded="onTabContentUnloaded">
                    ...
                </GridLayout>
            </mdt:TabContentItem>
            <mdt:TabContentItem>
                <GridLayout id="tab3" loaded="onTabContentLoaded" unloaded="onTabContentUnloaded">
                    ...
                </GridLayout>
            </mdt:TabContentItem>
            <mdt:TabContentItem>
                <GridLayout id="tab4" loaded="onTabContentLoaded" unloaded="onTabContentUnloaded">
                    ...
                </GridLayout>
            </mdt:TabContentItem>
</mdt:Tabs>
```

```
export function onTabContentLoaded(args: EventData) {
  console.log("loaded:");
  console.log(args.object);
}


export function onTabContentUnloaded(args: EventData) {
  console.log("unloaded:");
  console.log(args.object);
}
```

When swiping between the last two tabs (tab3 and tab3), I see the following output in the console:

> JS: selectedIndexChanged
> JS: 3
> JS: unloaded:
> JS: GridLayout<tab4>@main-page.xml:58:17;
> JS: loaded:
> JS: GridLayout<tab3>@main-page.xml:46:17;
> JS: selectedIndexChanged
> JS: 4
> JS: unloaded:
> JS: GridLayout<tab3>@main-page.xml:46:17;
> JS: loaded:
> JS: GridLayout<tab4>@main-page.xml:58:17;
> JS: selectedIndexChanged
> JS: 3
> JS: unloaded:
> JS: GridLayout<tab4>@main-page.xml:58:17;
> JS: loaded:
> JS: GridLayout<tab3>@main-page.xml:46:17;
> JS: selectedIndexChanged
> JS: 4
> JS: unloaded:
> JS: GridLayout<tab3>@main-page.xml:46:17;
> JS: loaded:
> JS: GridLayout<tab4>@main-page.xml:58:17;

-> Why is the tab4 ever unloaded? The offscreenTabLimit defaults to 1, so actually that tab should never be unloaded?


When setting `offscreenTabLimit` to 4 and start the app, I see the following initial output:

> JS: selectedIndexChanged
> JS: 0
> JS: loaded:
> JS: GridLayout<tab0>@main-page.xml:10:17;
> JS: loaded:
> JS: GridLayout<tab1>@main-page.xml:22:17;
> JS: loaded:
> JS: GridLayout<tab2>@main-page.xml:34:17;
> JS: loaded:
> JS: GridLayout<tab3>@main-page.xml:46:17;
> JS: loaded:
> JS: GridLayout<tab4>@main-page.xml:58:17;
> JS: unloaded:
> JS: GridLayout<tab1>@main-page.xml:22:17;
> JS: unloaded:
> JS: GridLayout<tab2>@main-page.xml:34:17;
> JS: unloaded:
> JS: GridLayout<tab3>@main-page.xml:46:17;
> JS: unloaded:
> JS: GridLayout<tab4>@main-page.xml:58:17;

So all tabs are loaded as expected, but then all tabs other than the first are unloaded again. 


Latest sample app:
[ns-custom-tabs.zip](https://github.com/nativescript-community/ui-material-components/files/8364639/ns-custom-tabs.zip)

**Comment by farfromrefug** [comment]
@felixkrautschuk i am talkig about loading on mdtabs biew creation. before you switch tab!
but you are right there seem to be a bug with offscreenTabLimit.
i ll look at it when i have the time. 
but again i would look at not loading listview content before the tab is actually showing.
you can see this behavior in almost any android native apps

**Comment by felixkrautschuk** [comment]
Yes I agree that loading listview content in navigatingTo event is not a good idea and I handle that differently in our production app. But this issue is only related to switching tabs with swiping gesture (even if the tabs were shown before).

**Comment by farfromrefug** [comment]
@felixkrautschuk i looked at the code of `offscreenTabLimit ` and i actually think everything is correct.
The thing is that N do something that i never liked which is called `load`/`unload`  on all but selected on each tab change.
And it might be an issue with `RadListView` as it might be reloading its data in `load` (which it should NOT do).
I think i wont fix this as it follows N way of doing things.
You can try switching to `@nativescript-community/ui-collectionview`, it should not reload anything and thus no lag

**Comment by felixkrautschuk** [comment]
Okay.... I forgot to comment the line `args.object.refresh()` inside my `onListViewLoaded` callback. I needed that line when loading the ObservableArray-content inside navigatingTo event, because in this case, the list items where only visible inside the first tab after app start, the other lists were empty.
When moving the loading process - as you told me - inside "tab shown" event, this problem does not occur. So i need no refresh call and then there is no lag when switching the tabs.

But I still do not understand why the Tabs plugin 7.0.2 still loads only the first tab ("tab0") on app start and not also tab1 even though offscreenTabLimit is 1. And when swiping, it is still unloading all tabs other than the current.
This is not related to RadListView, because I temporary replaced that with your community ui-collectionview and even with default ListView.

And this does not happen when switching back to Tabs plugin 6.2.19, while the N core version stays the same.

**Comment by farfromrefug** [comment]
@felixkrautschuk i think it creates the view but not call `onLoad`. If you can confirm there is something wrong i can look at it.
6.x version was totally different and not following N specs. 7.x is a full rewrite.

**Comment by jessorlisa** [comment]
I just stumbled across this as I also have issues with 7.x (albeit slightly different, I will create issues once I have a project for easy reproduction)....

@farfromrefug It seems the rewrite started already with [6.2.15](https://github.com/nativescript-community/ui-material-components/commit/4f71387601ad5ac64407804cc664bf34002132d6) and not only with 7.x? Which version should we stick to if we are not (yet) ready to update to 7.x? And another related question: Can I use version 6 with {N} core/runtime 8.2.x?

**Comment by farfromrefug** [comment]
@jessorlisa indeed stick with [v6.2.14](https://github.com/nativescript-community/ui-material-components/commit/750b56e352d255473933621e1466b3bd891f930d).
and yes you should be able to use it with 8.2.x though i cant ensure anything now.

@jessorlisa @felixkrautschuk i keep on looking at this. I see what changed from 6.x to 7.x. I can revert but i dont like it:
* in 6.x on each tab change load was called on selected `index` and unload for all items `< index` and `> index + offscreenTabLimit`
This means that your issue was already happening while navigating from your "heavy" tab to the next and back.
Also for all tabs for which `unload` is NOT called (inside `index / index + offscreenTabLimit`) then delegates are not removed which is the whole point of load/unload

My idea in 7.x is to not use `offscreenTabLimit` for load/unload so that delegate are always cleaned but view NOT destroyed. `offscreenTabLimit` is used to decide when to destroy views and re create them. 
This follows N "ways" and i think this is the way it should be.
If your page/components are correctly implemented then it should NOT create any issue. As i mentioned for example collectionview will NOT reload on load/unload. I have old sources of RadListView and i can say it should work too as it does not seem to reload on `load/unload` (except if it changed since then).

**Comment by felixkrautschuk** [comment]
I'm closing this, as it seems that nativescript-ui-listview 10.2.x fixes the issue.
