### ISSUE TITLE
[bottomSheet] Landscape the height does not work in Android

### ISSUE THREAD

**Issue by zeejay09** [nativescript-community/ui-material-components#377]
I have this problem, I set the height of the bottom sheet to 500 from 200. The code is just like the one in the readme. In portrait it looks okay:
![image](https://user-images.githubusercontent.com/30751791/160980884-60939bb1-9b15-4946-b12e-94c890d996a2.png)

However, when in landscape, the height does not take effect:
![image](https://user-images.githubusercontent.com/30751791/160980934-3a67e50b-6d5c-4f18-8dc5-fd70d140dbc4.png)

And if I changed it back to 200 or removed the height entirely, in landscape, it shows the same. I also tested this on a tablet, still the same in landscape.

The emulator is Android 10 and the Tablet is Android 11.

**Comment by farfromrefug** [comment]
@zeejay09 sadly it seems to be an issue with the native lib. 
you can try and reproduce in an android native app.and report it in the android material repo

**Comment by zeejay09** [comment]
@farfromrefug yeah that was what I was thinking also. Will report it to them, thanks.

**Comment by zeejay09** [comment]
It seems that they have already identified it but the fix is temporarily rolled back for further investigation.

https://github.com/material-components/material-components-android/issues/2221

This is for anybody that might stumble upon the same issue.
