### ISSUE TITLE
[BottomSheet][NS 8.2][iOS only] App hangs when opening a bottom sheet with DatePicker

### ISSUE THREAD

**Issue by MrSnoozles** [nativescript-community/ui-material-components#380]
### Which platform(s) does your issue occur on?
- iOS only, iPhone 13, iOS 15.2 (emulated) 

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.2.3
- Cross-platform modules: 8.2.2
- Runtime - ios: 8.2.3 
- Plugin(s): 7.0.3
- Xcode: 13.2.1

### Please, tell us how to recreate the issue in as much detail as possible. 
When the "inner" component of a bottom sheet contains a DatePicker, the app becomes unresponsive and has to be restarted. I noticed this behaviour after updating from NativeScript 8.1 to 8.2.

### Is there any code involved? 
[BottomSheetBug.zip](https://github.com/nativescript-community/ui-material-components/files/8514057/BottomSheetBug.zip)

**Comment by MrSnoozles** [comment]
Update:
If the inner component is wrapped in a `<Page>` tag, it works without hanging. But then the styling is off and I suppose there will be other side effects.

**Comment by farfromrefug** [comment]
@MrSnoozles It is actually a big issue with N which appeared in 8.2.0. Trying to pinpoint it but it is slow process

**Comment by farfromrefug** [comment]
@MrSnoozles Should be fixed in 7.0.4

**Comment by MrSnoozles** [comment]
Hi @farfromrefug .
I have to reopen this issue, unfortunately. It seems like there has been a regression between ui-material-bottomsheet 7.0.7 and 7.0.8.
When having a datepicker in a bottom sheet, the application now crashes immediately when closing the bottom sheet.
 
![nativescript-bottomsheet](https://user-images.githubusercontent.com/17496592/175498388-e20bbd47-cd7a-49cf-8498-c899db52bb2b.gif)


I already create an example repository so you can reproduce the issue: https://github.com/MrSnoozles/nativescript-bug-bottomsheet-datepicker


The error message is

~~~
NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'nativeViewProtected' of undefined
at
getAvailableSpaceFromParent(file: app/webpack:/bottomsheet-datepicker/node_modules/@nativescript-community/ui-material-bottomsheet/bottomsheet.ios.js:159:0)
at layoutView(file: app/webpack:/bottomsheet-datepicker/node_modules/@nativescript-community/ui-material-bottomsheet/bottomsheet.ios.js:109:0)
at MDLayoutViewController.viewDidLayoutSubviews(file: app/webpack:/bottomsheet-datepicker/node_modules/@nativescript-community/ui-material-bottomsheet/bottomsheet.ios.js:214:0)
~~~

**Comment by MrSnoozles** [comment]
Confirmed. It's fixed. Thank you
