### ISSUE TITLE
Bottom Sheet does not open when calling function from Vue Plugin

### ISSUE THREAD

**Issue by dangrima90** [nativescript-community/ui-material-components#387]
I have a bottom sheet component in a components library which I'd like to migrate to start using `@nativescript-community/ui-material-bottomsheet`. So to reduce the amount of code changes I'm trying to create a wrapper Vue Plugin using the `@nativescript-community/ui-material-bottomsheet` library which can then be imported into any NativeScript Vue application.

**Sample Plugin code**

```js
import NSBottomSheetPlugin from '@nativescript-community/ui-material-bottomsheet/vue';
import { install as BottomSheetPluginInstall } from '@nativescript-community/ui-material-bottomsheet';

const BottomSheetPlugin = {
  install(Vue: any, options: any) {
    const localVueInstance = Vue;

    const bottomSheetPlugin = Vue.prototype.$myBottomSheet;

    BottomSheetPluginInstall();
    localVueInstance.use(NSBottomSheetPlugin);

    bottomSheetPlugin.show = function(args: any) {
      console.log('show bottom sheet');
      console.log('component', args.component);

      localVueInstance.prototype.$showBottomSheet(args.component, args);
   };
};

export default BottomSheetPlugin;
```

The above code is installing the bottom sheet plugin and simply creating a wrapper function to expose the `$showBottomSheet` function. After using the plugin in an application it can then be called via `this.$myBottomSheet.show()`.

For some reason when the `show` function is called no bottom sheet is displayed. The console logs placed in the function do trigger which means that the function is being called. Out of curiosity I've tried calling similar functions from my own plugin like `$showModal` and `$navigateTo` which all resulted in the same result - the `show` function is called but then nothing happens.

Not sure if this is an issue from my end, the bottom sheet plugin or NativeScript Vue itself.

**Comment by farfromrefug** [comment]
@dangrima90 please add a try catch (it is a promise) on the `$showBottomSheet`. Without it it is hard to know what s happening

**Comment by dangrima90** [comment]
You're right, sorry my bad. So error catching the error on the Promise, the following error is being thrown:

`TypeError: Cannot read property 'showBottomSheet' of undefined`

Error is coming from: `node_modules/@nativescript-community/ui-material-bottomsheet/vue/index.js`, it looks like `this.nativeView` is `undefined`.

**Comment by farfromrefug** [comment]
@dangrima90 you got your error! it is not `localVueInstance.prototype.$showBottomSheet(args.component, args);`  but `localVueInstance.$showBottomSheet(args.component, args);`

**Comment by dangrima90** [comment]
Calling `$showBottomSheet` without the `prototype` results in: 

`TypeError: localVueInstance.$showBottomSheet is not a function`.

In the error I've sent previously it's `showBottomSheet` that is causing the issue and not `$showBottomSheet`.

Meaning that this line is failing:

https://github.com/nativescript-community/ui-material-components/blob/96cfe1ff834ee2f99b757bc9cd7db9daafcda0df/src/bottomsheet/vue/index.ts#L50

**Comment by dangrima90** [comment]
I'm sorry, I'm not understanding how `$showBottomSheet` is being "called too soon". The code is a simple wrapper function - the `$showBottomSheet` is not called by the plugin's `install()` function. It is called when an application calls `this.$myBottomSheet.show(...)`.

I've created a sample repository where you can see the issue: https://github.com/dangrima90/bottom-sheet-plugin-test.

* The [plugin code](https://github.com/dangrima90/bottom-sheet-plugin-test/blob/main/plugins/bottomSheetPlugin.js) can be found the `plugins` folder.
* The application will show two buttons one to load the bottom sheet via the custom plugin and another calling the plugin directly.
* When using the first button you'll see via the console logs that `$showBottomSheet` function is not `undefined`.
* You'll see that the bottom sheet plugin is being installed correctly because even though the `Vue.use()` for the `nativescript-community` plugin and `install` are being called in the custom plugin, when using the second button in the demo app the bottom sheet loads as expected.

**Comment by farfromrefug** [comment]
@dangrima90 my bad wrongly read your code. 
sorry I want to help you.
now the $showBortomSheet should be called on a vue instance not the prototype.
I can't do muchore seeing I am not in front of a computer those days. but as I said please look at the demo app which works just fine

**Comment by dangrima90** [comment]
@farfromrefug I've managed to implement a workaround for this issue. I investigated a bit what is happening in this case and why `this.nativeView` was `undefined` when being called via the custom plugin.

I've managed to replicate the same issue when trying to use NativeScript-Vue's `$showModal` function. In this case `nativeView` is not found in this [line](https://github.com/nativescript-vue/nativescript-vue/blob/main/platform/nativescript/plugins/modal-plugin.js#L103).

Back to the my custom bottom sheet plugin, when logging the `this` I got different results between the custom plugin and calling your plugin directly. It seems that the context is different in this scenario. My guess is via the custom plugin the context is the Vue instance in the plugin whilst when calling the plugin directly the context is the App Vue instance.

Now instead of implementing a custom function that binds to the Vue instance I've implemented a global mixin, which means that when the `this` is called it will reference the app context.

**Code Sample**

```js
import NSBottomSheetPlugin from "@nativescript-community/ui-material-bottomsheet/vue";
import { install as BottomSheetPluginInstall } from "@nativescript-community/ui-material-bottomsheet";

const BottomSheetPlugin = {
  install(Vue) {
    const localVueInstance = Vue;

    BottomSheetPluginInstall();
    localVueInstance.use(NSBottomSheetPlugin);

    localVueInstance.mixin({
      methods: {
        $_showBottomSheet(args) {
          this.$showBottomSheet(args.component, args);
        },
      },
    });
  },
};

export default BottomSheetPlugin;
```

**Usage Sample**

```js
export default {
  methods: {
    showBottomSheet() {
      this.$_showBottomSheet({
        component: BottomSheetContent,
      });
    },
};
```

**Comment by farfromrefug** [comment]
@dangrima90 i think there is something wrong in your app code. Your mixin actually does nothing except adding a function in between (and changing the args type).
Sorry you got this trouble
