### ISSUE TITLE
CocoaPods for MaterialComponents/TextControls fails

### ISSUE THREAD

**Issue by dangrima90** [nativescript-community/ui-material-components#392]
A bit of a weird issue but I can't seem to figure out what the issue is. When trying to use `@nativescript-community/ui-material-textfield` I can't use version 7 of the package on iOS.

I'm always getting the following error:

![image](https://user-images.githubusercontent.com/36479149/175027036-ec72ecf7-508f-4215-b40b-fb57c721ee13.png)

The screenshot displays the error being shown for `MaterialComponents/TextControls+UnderlinedTextFields`, but each time I try to run a different `MaterialComponents/TextControls` Pod gets listed. Basically it's always one of the following:

```
pod 'MaterialComponents/TextControls+FilledTextFields'
pod 'MaterialComponents/TextControls+UnderlinedTextFields'
pod 'MaterialComponents/TextControls+OutlinedTextFields'
pod 'MaterialComponents/TextControls+FilledTextFieldsTheming'
pod 'MaterialComponents/TextControls+UnderlinedTextFieldsTheming'
pod 'MaterialComponents/TextControls+OutlinedTextFieldsTheming'
```

Which of course it's understandable as these are the dependencies of `@nativescript-community/ui-material-textfield`.

I've tried countless things from updating pods, to reinstalling pods, clearing the cache, trying to force the pods version myself, trying different 7.x versions - but no luck whatsoever.

With `@nativescript-community/ui-material-textfield` version 6 I've seen no problems. However I'm at a point where I need to use both `@nativescript-community/ui-material-textfield` and `@nativescript-community/ui-material-bottomsheet`. Since I need bottom sheet v7, all material components should be using v7 so that the core is using the same version. However I'm stuck as when trying to run on iOS it always fails due to `MaterialComponents/TextControls`.

I understand that it might be difficult to deduce what the issue is, but any idea what could be the problem here?

**Comment by farfromrefug** [comment]
@dangrima90 did you run `pod repo update` ?

**Comment by dangrima90** [comment]
@farfromrefug Yes ran `pod repo update`. Same goes for `pod install --repo-update`. I've also tried clearing the cache: `pod cache clean --all`. No luck

**Comment by farfromrefug** [comment]
@dangrima90 you can look in the podfile lock to see what version is installing. It should be the latest.
If not then something is preventing you from installing latest from cocoapod. maybe you need `platform :ios, '10.0'` in your pdofile?

**Comment by dangrima90** [comment]
Unfortunately I can't see what's in the podfile lock since the build is failing the file is not created.

I added `platform :ios, '10.0'` to my podfile but still the same result:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/36479149/175040249-d8651f8a-733d-4edf-94d4-0f9e427fa166.png">

**Comment by dangrima90** [comment]
@farfromrefug I've analysed the generated podfile and here's all the references to `MaterialComponents`:

```
# Begin Podfile - /Users/gria001/Code/transfers/node_modules/@nativescript-community/ui-material-textfield/platforms/ios/Podfile
pod 'MaterialComponents/TextControls+FilledTextFields'
pod 'MaterialComponents/TextControls+UnderlinedTextFields'
pod 'MaterialComponents/TextControls+OutlinedTextFields'
pod 'MaterialComponents/TextControls+FilledTextFieldsTheming'
pod 'MaterialComponents/TextControls+UnderlinedTextFieldsTheming'
pod 'MaterialComponents/TextControls+OutlinedTextFieldsTheming'
# pod 'MaterialComponents/TextFields+Theming'
# End Podfile

# Begin Podfile - /Users/gria001/Code/transfers/node_modules/@nativescript/core/platforms/ios/Podfile
# platform :ios, '12.0'
use_frameworks!

pod 'MaterialComponents/Tabs', '~> 94.5'

def post_install_nativescript_core_0 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
# End Podfile

# Begin Podfile - /Users/gria001/Code/transfers/node_modules/@nativescript-community/ui-material-core/platforms/ios/Podfile
pod 'MaterialComponents/schemes/Color'
pod 'MaterialComponents/Ripple'

# End Podfile
```

Could any of these be creating a problem?

**Comment by dangrima90** [comment]
Ehh thought so - We're stuck with NativeScript 7 unfortunately 😞

**Comment by dangrima90** [comment]
Asking as I saw this a few moments ago (https://github.com/NativeScript/nativescript-cli/issues/5061) But I'm not so sure how it can be used.

**Comment by farfromrefug** [comment]
@dangrima90 you can create a hook to modify the podfile and remove it. This is what i did in 5.x and 6.x of material components. You should be able to find it in git history

**Comment by dangrima90** [comment]
Alright time to go back in history then 😆 thanks for your help

**Comment by farfromrefug** [comment]
@dangrima90 wow did not know about that option !!!

**Comment by dangrima90** [comment]
From what I'm seeing in NativeScript 6 it used to exist but it was a boolean in a JSON file.

Now for NativeScript 7 I'm seeing a TypeScript config file and not a JSON one. Now for some reason the type is set to a string - I thought let me try true as a string instead. Just my luck it worked :)
