### ISSUE TITLE
[Tabs] [iOS] Tabs don't swipe even with swipeEnabled = true after the first swipe

### ISSUE THREAD

**Issue by msl2000** [nativescript-community/ui-material-components#393]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- ios 

### Please, provide the following version numbers that your issue occurs with:

CLI: 8.2.3
Cross-platform modules: 8.2.3
Runtime(s):
"@nativescript/android": "^8.2.2",
"@nativescript/ios": "~8.3.0",
Plugin(s):Tabs version "^7.0.22"

### Please, tell us how to recreate the issue in as much detail as possible. 
I simply used the example code in the documentation. The swipe works perfectly fine on Android but not on iOS.

After the first swipe to another tab, I cannot swipe to other tabs anymore. It does the pull animation but doesnt make the switch.

![ezgif-1-e5acaccc9d](https://user-images.githubusercontent.com/18165861/175245395-7bef1889-e467-4b5c-8dd9-746a69812318.gif)

### Is there any code involved? 
        <MDTabs selectedIndex="1">
            <MDTabStrip>
                <MDTabStripItem>
                    <Label text="Home"></Label>
                </MDTabStripItem>
                <MDTabStripItem class="special">
                    <Label text="Account"></Label>
                </MDTabStripItem>
                <MDTabStripItem class="special">
                    <Label text="Search"></Label>
                </MDTabStripItem>
            </MDTabStrip>
    
            <MDTabContentItem>
                <GridLayout>
                    <Label text="Home Page" class="h2 text-center"></Label>
                </GridLayout>
            </MDTabContentItem>
            <MDTabContentItem>
                <GridLayout>
                    <Label text="Account Page" class="h2 text-center"></Label>
                </GridLayout>
            </MDTabContentItem>
            <MDTabContentItem>
                <GridLayout>
                    <Label text="Search Page" class="h2 text-center"></Label>
                </GridLayout>
            </MDTabContentItem>
        </MDTabs>

**Comment by farfromrefug** [comment]
@msl2000 should be fixed in 7.0.23

**Comment by msl2000** [comment]
Perfect. This works.
