### ISSUE TITLE
[Feature request][Floating Action Button] Swipe animation

### ISSUE THREAD

**Issue by danouche93** [nativescript-community/ui-material-components#399]
I changed the plugin I used for floating button from @nstudio/nativescript-floatingactionbutton to this plugin. The old one had an option to show and hide the button when scrolling a ListView with an animation thanks to "hideOnSwipeOfView" attribute.
Is it possible to have this feature with this plugin?

Thanks

**Comment by farfromrefug** [comment]
@danouche93 you can do it with N scroll events and animations. Won't be part of this plugin. You might even fins the code in the nstudio plugin
