### ISSUE TITLE
[BottomNavigationBar] set disabled color

### ISSUE THREAD

**Issue by boris01** [nativescript-community/ui-material-components#401]
Hi,
I'm trying to find a way to set additional - disabled color for the tab, in case the tab isSelectable property is false.
Is there a way to do this with the BottomNavigationBar?

Thanks

**Comment by farfromrefug** [comment]
@boris01 you can do this with css and pseudo selector like this:
```css
myClass[isSelectable="false"] {}
```

**Comment by boris01** [comment]
@farfromrefug Thank you for you help!
Unfortunately it is not working with this pseudo selector  myClass[isSelectable="false"]
Can you give a little example please?
