### ISSUE TITLE
How can I update the version of androidXMaterial library to Material3

### ISSUE THREAD

**Issue by vallemar** [nativescript-community/ui-material-components#414]
How can I update the version of this library: https://github.com/nativescript-community/ui-material-components/blob/master/packages/core/platforms/android/include.gradle#L3.

I want to update `androidXMaterial`  to 1.6.1 but I don't know how to pass it to the plugin

Doc: https://m3.material.io/libraries/mdc-android/getting-started

I want to update it only in my application and there seems to be some way to indicate it in the project. Another question would be if we could update to the version with Material3 by default

**Comment by farfromrefug** [comment]
@vallemar Here is how you can do it https://github.com/Akylas/alpimaps/blob/master/App_Resources/Android/before-plugins.gradle#L12

**Comment by vallemar** [comment]
@farfromrefug  You're a great person!!!!!
