### ISSUE TITLE
[android] Dialog button invisible

### ISSUE THREAD

**Issue by kefahB** [nativescript-community/ui-material-components#417]
Hi @farfromrefug 

I didn't understand what should I do in order to getting the color work in android ? can you advise me please ?

<img width="222" alt="Capture d’écran 2022-10-28 à 16 26 28" src="https://user-images.githubusercontent.com/18148534/198587437-0852e654-3e80-4e51-b250-6d392c3c2761.png">

**Comment by farfromrefug** [comment]
The issue is with your android theme.I am on my phone right now. But a simple search for android material theme colors will show you how to do it

**Comment by kefahB** [comment]
thanks
