### ISSUE TITLE
Types missing for Angular Bottomsheet: ui-material-bottomsheet/angular missing index.d.ts file

### ISSUE THREAD

**Issue by CodeWitchJosie** [nativescript-community/ui-material-components#441]
### Which platform(s) does your issue occur on?
- Both

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.5.3

### Please, tell us how to recreate the issue in as much detail as possible. 
See StackBlitz here: https://stackblitz.com/edit/nativescript-stackblitz-templates-fvvxry?file=src/app/app.module.ts
Code cannot compile due to missing index.d.ts file under node_modules/@nativescript-community/ui-material-bottomsheet/angular/

**Comment by vallemar** [comment]
I put it here in addition to discord in case anyone else has this problem

@farfromrefug  Is a problem of last release, use 7.0.42

```
npm install @nativescript-community/ui-material-bottomsheet@7.0.42
```

**Comment by farfromrefug** [comment]
@vallemar thanks I'll look a it tosay

**Comment by CodeWitchJosie** [comment]
@farfromrefug Confirmed working for us!
