### ISSUE TITLE
[Request] Border radius for bottom sheet

### ISSUE THREAD

**Issue by dammynex** [nativescript-community/ui-material-components#443]
I'd like to request if an option for borderRadius could be added for the bottom sheet..

**Comment by vallemar** [comment]
@dammynex use the option `transparent: true` and set `background` and 'border-radius' to your main content of BottomSheet. 

you can customize everything you have inside the BottomSheet!

**Comment by dammynex** [comment]
@vallemar  That worked.

Thank you!
