### ISSUE TITLE
[BottomSheet] No content shown when used with RAD SideDrawer

### ISSUE THREAD

**Issue by alexander-mai** [nativescript-community/ui-material-components#462]
An Empty white BottomSheet is shown, when it is used in Combination with RAD SideDrawer as Root-Element.

### Which platform(s) does your issue occur on?
- iOS 17.4
- emulator and device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.7.0
- Cross-platform modules: 8.7.2
- Runtime(s): 8.7.1
- Plugin(s):
  - @nativescript-community/ui-material-bottomsheet: 7.2.43+
  - nativescript-ui-sidedrawer: 15.2.3

### Please, tell us how to recreate the issue in as much detail as possible. 
Create an app with nativescript-ui-sidedrawer as root element. An opened bottomSheet is only white without any content.
On Android is the content of the bottomsheet correctly shown.
The problem exists since ui-material-bottomsheet version 7.2.43

### Is there any code involved? 
 - Example project: https://github.com/alexander-mai/nativescript-ui-sidedrawer-and-bottomsheet-problem-example/

**Comment by farfromrefug** [comment]
@alexander-mai sorry to hear that. If i find time i ll take a look, but i dont support RAD sidedrawer (too complex, too old, and not open source). I would advise to use `@nativescript-community/ui-drawer`

**Comment by alexander-mai** [comment]
Thank you @farfromrefug for your fast response.
I would like to use @nativescript-community/ui-drawer, but it is not possible to use it as root element afaik. Has this changed in the last month?

**Comment by farfromrefug** [comment]
@alexander-mai not sure why it would not be possible. Do you have a link to an error ?

**Comment by alexander-mai** [comment]
I have tested it some years ago and there is also an Issue about the root problem: https://github.com/nativescript-community/ui-drawer/issues/3.
I will give it a new try in the next days.

**Comment by JWiseCoder** [comment]
This issue was caused by https://github.com/nativescript-community/ui-material-components/commit/9a524e01a58cfda2a20800427c874f3cb5d96950

**Comment by farfromrefug** [comment]
@JWiseCoder thanks for investigating this! Indeed could be the issue. I ll take a look next week

**Comment by JWiseCoder** [comment]
@farfromrefug - After some more testing, found it works on 7.2.11, but breaks on 7.2.12 (and thereafter).  I think it was this commit where the parent was first being overridden: https://github.com/nativescript-community/ui-material-components/commit/ae4d6cc89fd6f5a13f8542be5e93777855605878

**Comment by farfromrefug** [comment]
@alexander-mai @JWiseCoder should be fixed in latest!

**Comment by alexander-mai** [comment]
I have tested the changed from your pull request in my app with the current version of the bottomsheet and the RadSidedrawer as root element. It works perfectly.

Thank you very much @farfromrefug.

**Comment by farfromrefug** [comment]
@alexander-mai can we close this now?

**Comment by alexander-mai** [comment]
Yes, I think so.
