### ISSUE TITLE
IOS 17.5.1 keyboard glitch on some batches on iphone 14+models(not all)

### ISSUE THREAD

**Issue by lcodetechgitrep** [nativescript-community/ui-material-components#465]
- iOS
- 17.5.1
- iphone 14 plus (some devices only)

Material components version 124.2.0
App built using xcode 14.2 (not xcode 15)

This has been reported by some users who use iphone 14 plus models, the material textfield when interacted with tries to show the keyboard, but dismisses it immediately, and this is happening on some iphone 14+ devices only, we have one iphone 14 plus device and we tried to recreate it, but its working fine on our device. This happened after the recent ios 17.5.1 update, works on other devices, not sure how to recreate or fix this issue. The ios UITextfield works fine.

**Comment by farfromrefug** [comment]
@lcodetechgitrep thanks for the report. For me to be able to look at this i ll need a simple repro example project showing the issue. I ll leave this open for a while. If there is not activity after that i ll close it. Hope you understand

**Comment by lcodetechgitrep** [comment]
hi thanks for responding, i myself am not able to simulate this on a similar device, might need a bit of time to reproduce this.
